import type { Item } from '../../../types/content';

// Ítems recuperados a mano desde el preguntero original (reference/EJERCITACION-
// FISICA.pdf). El importador los había roto al fusionar las columnas de
// opciones; acá se reconstruyen con las opciones reales y la respuesta
// verificada. Reemplazan a los fis-imp-* deprecados equivalentes.
export const items: Item[] = [
  {
    id: 'fis-rec-0090',
    institutions: ['UNC', 'UNSa'],
    subject: 'fisica',
    block: 'planteo_de_ecuaciones',
    topic: 'planteo_de_ecuaciones',
    track: 'practico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 2,
    stem: 'Una bacteria duplica su cantidad de colonias por minuto. Si a las 8:00 pm se cultiva una colonia y a las 8:17 pm se observa la mitad de la placa cubierta, ¿a qué hora se llenará toda la superficie?',
    choices: [
      { id: 'a', text: '8:18 pm', correct: true },
      { id: 'b', text: '8:34 pm', correct: false },
      { id: 'c', text: '9:00 pm', correct: false },
      { id: 'd', text: '16:34 pm', correct: false },
      { id: 'e', text: 'Ninguna es correcta', correct: false },
    ],
    explanation:
      'Como se duplica cada minuto, si a las 8:17 está la mitad, un minuto después (una duplicación más) se completa: 8:18 pm.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 12, "Planteo de Ecuaciones").',
  },
  {
    id: 'fis-rec-0094',
    institutions: ['UNC', 'UNSa'],
    subject: 'fisica',
    block: 'funcion_lineal',
    topic: 'funcion_lineal',
    track: 'practico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 2,
    stem: 'Si el punto (p ; 4) pertenece a la recta 3x − 2y = 7, entonces "p" vale:',
    choices: [
      { id: 'a', text: '5', correct: true },
      { id: 'b', text: '−5', correct: false },
      { id: 'c', text: '1/3', correct: false },
      { id: 'd', text: '−1/3', correct: false },
      { id: 'e', text: '5/2', correct: false },
    ],
    explanation:
      'Reemplazando y = 4: 3p − 2·4 = 7 → 3p − 8 = 7 → 3p = 15 → p = 5.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 5, "Función Lineal").',
  },
  {
    id: 'fis-rec-0393',
    institutions: ['UNC', 'UNSa'],
    subject: 'fisica',
    block: 'hidrostatica',
    topic: 'hidrostatica',
    track: 'practico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 2,
    stem: '¿Qué presión ejerce la atmósfera, considerando su valor normal, sobre una superficie circular de 5 cm de radio?',
    choices: [
      { id: 'a', text: '1013×10⁵ Pa', correct: false },
      { id: 'b', text: '1 013 250 din/cm²', correct: true },
      { id: 'c', text: '78,54 Pa', correct: false },
      { id: 'd', text: '78,54 atm', correct: false },
      { id: 'e', text: '78,54×10⁸ Pa', correct: false },
    ],
    explanation:
      'La presión no depende del área: la presión atmosférica normal es 101 325 Pa = 1 013 250 din/cm² (1 Pa = 10 din/cm²). El radio de 5 cm es un dato distractor.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 6, "Hidrostática").',
  },
  {
    id: 'fis-rec-0554',
    institutions: ['UNC', 'UNSa'],
    subject: 'fisica',
    block: 'gases',
    topic: 'gases',
    track: 'practico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 3,
    stem: 'Una mascarilla suministra 65 % de aire atmosférico y el resto (35 %) es oxígeno medicinal puro. Si el aire atmosférico tiene 21 % de O₂, ¿qué porcentaje total de oxígeno inhala el paciente?',
    choices: [
      { id: 'a', text: '21 %', correct: false },
      { id: 'b', text: '49 %', correct: true },
      { id: 'c', text: '56 %', correct: false },
      { id: 'd', text: '65 %', correct: false },
      { id: 'e', text: '12 %', correct: false },
    ],
    explanation:
      'O₂ aportado por el aire: 65 % × 21 % = 13,65 %. Más el O₂ puro: 35 %. Total ≈ 13,65 % + 35 % = 48,65 % ≈ 49 %.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 68, "Gases").',
  },

  // --- Reescritos a partir de ejercicios integradores multi-parte ---
  {
    id: 'fis-rec-0446',
    institutions: ['UNC', 'UNSa'],
    subject: 'fisica',
    block: 'trabajo_y_energia',
    topic: 'trabajo_y_energia',
    track: 'practico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 3,
    stem: 'Una esfera de plástico de radio 5 cm y densidad 0,5 g/cm³ se lanza con una energía cinética de 0,1309 J. ¿Con qué velocidad se lanza?',
    choices: [
      { id: 'a', text: '1 m/s', correct: true },
      { id: 'b', text: '2 m/s', correct: false },
      { id: 'c', text: '0,5 m/s', correct: false },
      { id: 'd', text: '10 m/s', correct: false },
    ],
    explanation:
      'Volumen = (4/3)π(5)³ ≈ 523,6 cm³ → masa = 0,5 g/cm³ × 523,6 ≈ 261,8 g = 0,2618 kg. De Ec = ½mv²: v = √(2·0,1309/0,2618) = √1 = 1 m/s.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Reescrito del preguntero (nº 61, "Hidrostática"), originalmente integrador multi-parte.',
  },
  {
    id: 'fis-rec-0616',
    institutions: ['UNC', 'UNSa'],
    subject: 'fisica',
    block: 'electrodinamica',
    topic: 'electrodinamica',
    track: 'practico',
    type: 'single_choice',
    frequency: 'baja',
    difficulty: 3,
    stem: 'Si a través de un canal iónico pasan 3 iones Mg²⁺ en 2 nanosegundos, ¿cuál es la intensidad de la corriente iónica? (carga elemental e = 1,6×10⁻¹⁹ C)',
    choices: [
      { id: 'a', text: '4,8×10⁻¹⁰ A', correct: true },
      { id: 'b', text: '2,4×10⁻¹⁰ A', correct: false },
      { id: 'c', text: '9,6×10⁻¹⁹ A', correct: false },
      { id: 'd', text: '1,6×10⁻¹⁹ A', correct: false },
    ],
    explanation:
      'Cada Mg²⁺ aporta 2 cargas: q = 3 × 2 × 1,6×10⁻¹⁹ = 9,6×10⁻¹⁹ C. Intensidad I = q/t = 9,6×10⁻¹⁹ / 2×10⁻⁹ = 4,8×10⁻¹⁰ A.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Reescrito del preguntero (nº 31, "Electrodinámica"), originalmente integrador multi-parte.',
  },
];
