import type { Item } from '../../../types/content';

// Alfabetización Académica: teoría de textos y discurso (secuencias, coherencia
// y cohesión, conectores, paratextos, resumen). Son ítems autónomos (sin texto
// base) → aptos para el simulacro UNSa. Temario UNSa (Módulo Alfabetización).
// Original. Distractores balanceados.
export const items: Item[] = [
  {
    id: 'aau-teo-0001',
    institutions: ['UNSa'],
    subject: 'alfabetizacion',
    block: 'alfabetizacion_academica',
    topic: 'tipos_de_secuencia',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'alta',
    difficulty: 1,
    stem: 'Un texto que **defiende una postura mediante razones** para convencer al lector corresponde a una secuencia:',
    choices: [
      { id: 'a', text: 'Argumentativa.', correct: true },
      {
        id: 'b',
        text: 'Narrativa.',
        correct: false,
        feedback: 'La narrativa relata hechos en el tiempo, no defiende una postura.',
      },
      {
        id: 'c',
        text: 'Descriptiva.',
        correct: false,
        feedback: 'La descriptiva presenta rasgos de un objeto o lugar, no argumenta.',
      },
      {
        id: 'd',
        text: 'Instruccional.',
        correct: false,
        feedback: 'La instruccional indica pasos a seguir, no sostiene una tesis.',
      },
    ],
    explanation:
      'La secuencia argumentativa presenta una tesis y la sostiene con argumentos para persuadir. Es típica de editoriales, ensayos y notas de opinión.',
    source: 'original',
    version: 1,
    status: 'active',
  },
  {
    id: 'aau-teo-0002',
    institutions: ['UNSa'],
    subject: 'alfabetizacion',
    block: 'alfabetizacion_academica',
    topic: 'tipos_de_secuencia',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'alta',
    difficulty: 1,
    stem: 'Un texto cuya finalidad es **informar y explicar** un tema de manera objetiva corresponde a una secuencia:',
    choices: [
      {
        id: 'a',
        text: 'Argumentativa, porque busca convencer al lector.',
        correct: false,
        feedback: 'Explicar objetivamente no es lo mismo que defender una postura.',
      },
      {
        id: 'b',
        text: 'Expositiva, porque presenta información de forma clara.',
        correct: true,
      },
      {
        id: 'c',
        text: 'Narrativa, porque relata acciones encadenadas.',
        correct: false,
        feedback: 'La narrativa cuenta hechos; exponer es explicar un tema.',
      },
      {
        id: 'd',
        text: 'Dialogal, porque reproduce una conversación.',
        correct: false,
        feedback: 'La secuencia dialogal reproduce intercambios entre voces, no explica.',
      },
    ],
    explanation:
      'La secuencia expositiva-explicativa transmite información de manera objetiva y ordenada (definiciones, causas, comparaciones). Predomina en textos de estudio y de divulgación.',
    source: 'original',
    version: 1,
    status: 'active',
  },
  {
    id: 'aau-teo-0003',
    institutions: ['UNSa'],
    subject: 'alfabetizacion',
    block: 'alfabetizacion_academica',
    topic: 'conectores',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'alta',
    difficulty: 2,
    stem: 'En la oración "Estudió mucho; **sin embargo**, no aprobó", el conector marcado expresa una relación de:',
    choices: [
      {
        id: 'a',
        text: 'Oposición o contraste entre las ideas.',
        correct: true,
      },
      {
        id: 'b',
        text: 'Causa que explica el resultado.',
        correct: false,
        feedback: '"Sin embargo" no introduce una causa; contrapone ideas.',
      },
      {
        id: 'c',
        text: 'Consecuencia derivada de lo anterior.',
        correct: false,
        feedback: 'La consecuencia se marca con "por lo tanto", "así que"; no con "sin embargo".',
      },
      {
        id: 'd',
        text: 'Orden temporal entre dos hechos.',
        correct: false,
        feedback: 'El orden temporal usa "luego", "después"; "sin embargo" indica contraste.',
      },
    ],
    explanation:
      '"Sin embargo" es un conector adversativo: contrapone dos ideas (se esperaba aprobar, pero no ocurrió). Otros adversativos: pero, no obstante, aunque.',
    source: 'original',
    version: 1,
    status: 'active',
  },
  {
    id: 'aau-teo-0004',
    institutions: ['UNSa'],
    subject: 'alfabetizacion',
    block: 'alfabetizacion_academica',
    topic: 'conectores',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 2,
    stem: '¿Cuál de estos conectores expresa una relación de **causa-consecuencia**?',
    choices: [
      {
        id: 'a',
        text: 'Además.',
        correct: false,
        feedback: '"Además" agrega información (relación aditiva).',
      },
      {
        id: 'b',
        text: 'Por ejemplo.',
        correct: false,
        feedback: '"Por ejemplo" introduce una ejemplificación.',
      },
      {
        id: 'c',
        text: 'Por lo tanto.',
        correct: true,
      },
      {
        id: 'd',
        text: 'En cambio.',
        correct: false,
        feedback: '"En cambio" marca contraste, no causa-consecuencia.',
      },
    ],
    explanation:
      '"Por lo tanto" es un conector consecutivo: introduce el resultado que se deriva de lo dicho antes. Otros: en consecuencia, así que, de modo que.',
    source: 'original',
    version: 1,
    status: 'active',
  },
  {
    id: 'aau-teo-0005',
    institutions: ['UNSa'],
    subject: 'alfabetizacion',
    block: 'alfabetizacion_academica',
    topic: 'coherencia_y_cohesion',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 3,
    stem: 'La diferencia entre **coherencia** y **cohesión** de un texto es que:',
    choices: [
      {
        id: 'a',
        text: 'La coherencia es la unidad de sentido global; la cohesión, los recursos lingüísticos que enlazan las partes.',
        correct: true,
      },
      {
        id: 'b',
        text: 'La coherencia son las marcas gramaticales; la cohesión, el tema general del texto.',
        correct: false,
        feedback: 'Están invertidas: la coherencia es el sentido global y la cohesión, las marcas que enlazan.',
      },
      {
        id: 'c',
        text: 'La coherencia y la cohesión son sinónimos y se refieren a lo mismo.',
        correct: false,
        feedback: 'No son lo mismo: una es de sentido global, la otra de enlaces lingüísticos.',
      },
      {
        id: 'd',
        text: 'La coherencia depende de la ortografía; la cohesión, de la extensión del texto.',
        correct: false,
        feedback: 'Ni la ortografía ni la extensión definen estos conceptos.',
      },
    ],
    explanation:
      'La coherencia es la unidad semántica global (que el texto "tenga sentido" y progrese sobre un tema). La cohesión son los recursos lingüísticos (conectores, referencia, sinonimia) que enlazan las oraciones en la superficie.',
    source: 'original',
    version: 1,
    status: 'active',
  },
  {
    id: 'aau-teo-0006',
    institutions: ['UNSa'],
    subject: 'alfabetizacion',
    block: 'alfabetizacion_academica',
    topic: 'coherencia_y_cohesion',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 2,
    stem: 'En "Compré un libro. **Lo** leí en dos días", la palabra "lo" es un recurso de cohesión por:',
    choices: [
      {
        id: 'a',
        text: 'Referencia (pronominalización), porque remite a un elemento ya nombrado.',
        correct: true,
      },
      {
        id: 'b',
        text: 'Sinonimia, porque reemplaza una palabra por otra de igual significado.',
        correct: false,
        feedback: '"Lo" no es un sinónimo: es un pronombre que remite a "el libro".',
      },
      {
        id: 'c',
        text: 'Repetición, porque vuelve a nombrar la misma palabra.',
        correct: false,
        feedback: 'No se repite la palabra "libro"; se la reemplaza por un pronombre.',
      },
      {
        id: 'd',
        text: 'Conexión, porque une dos oraciones con un conector.',
        correct: false,
        feedback: '"Lo" no es un conector, sino un pronombre de referencia.',
      },
    ],
    explanation:
      'La cohesión gramatical por referencia usa pronombres (como "lo") para remitir a un elemento ya mencionado ("el libro"), evitando repetirlo.',
    source: 'original',
    version: 1,
    status: 'active',
  },
  {
    id: 'aau-teo-0007',
    institutions: ['UNSa'],
    subject: 'alfabetizacion',
    block: 'alfabetizacion_academica',
    topic: 'paratextos',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 1,
    stem: '¿Cuál de los siguientes es un elemento **paratextual**?',
    choices: [
      {
        id: 'a',
        text: 'El título del texto.',
        correct: true,
      },
      {
        id: 'b',
        text: 'La idea principal de un párrafo.',
        correct: false,
        feedback: 'La idea principal es parte del contenido, no del paratexto.',
      },
      {
        id: 'c',
        text: 'Un argumento del autor.',
        correct: false,
        feedback: 'Un argumento pertenece al desarrollo del texto, no al paratexto.',
      },
      {
        id: 'd',
        text: 'La conclusión del escrito.',
        correct: false,
        feedback: 'La conclusión forma parte del cuerpo del texto, no es un paratexto.',
      },
    ],
    explanation:
      'Los paratextos rodean al texto y orientan la lectura: título, subtítulo, epígrafe, imágenes, gráficos, destacados, índices. Ayudan a anticipar el contenido.',
    source: 'original',
    version: 1,
    status: 'active',
  },
  {
    id: 'aau-teo-0008',
    institutions: ['UNSa'],
    subject: 'alfabetizacion',
    block: 'alfabetizacion_academica',
    topic: 'resumen',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 2,
    stem: 'Al elaborar un **resumen**, la regla de "generalización" consiste en:',
    choices: [
      {
        id: 'a',
        text: 'Reemplazar una serie de elementos por un término que los englobe.',
        correct: true,
      },
      {
        id: 'b',
        text: 'Copiar textualmente las oraciones más largas del texto.',
        correct: false,
        feedback: 'Un resumen no copia textualmente; reformula y condensa.',
      },
      {
        id: 'c',
        text: 'Agregar opiniones personales sobre el tema tratado.',
        correct: false,
        feedback: 'El resumen no incorpora opiniones propias del lector.',
      },
      {
        id: 'd',
        text: 'Ampliar el texto con ejemplos y detalles adicionales.',
        correct: false,
        feedback: 'Resumir es reducir, no ampliar con más detalles.',
      },
    ],
    explanation:
      'Entre las reglas del resumen, la generalización sustituye varios elementos por uno más general (por ejemplo, "manzanas, peras y uvas" → "frutas"). Otras reglas: supresión, selección y construcción.',
    source: 'original',
    version: 1,
    status: 'active',
  },
  {
    id: 'aau-teo-0009',
    institutions: ['UNSa'],
    subject: 'alfabetizacion',
    block: 'alfabetizacion_academica',
    topic: 'discurso_academico',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 2,
    stem: 'La principal diferencia entre el **discurso científico** y el de **divulgación científica** es que este último:',
    choices: [
      {
        id: 'a',
        text: 'Está dirigido a un público general y usa un lenguaje más accesible.',
        correct: true,
      },
      {
        id: 'b',
        text: 'Se dirige solo a especialistas y emplea tecnicismos rigurosos.',
        correct: false,
        feedback: 'Eso describe al discurso científico, no al de divulgación.',
      },
      {
        id: 'c',
        text: 'Carece por completo de base en investigaciones reales.',
        correct: false,
        feedback: 'La divulgación se apoya en la ciencia; la traduce, no la inventa.',
      },
      {
        id: 'd',
        text: 'No puede usar ejemplos ni comparaciones para explicar.',
        correct: false,
        feedback: 'Al contrario: la divulgación abunda en ejemplos y analogías para acercar el tema.',
      },
    ],
    explanation:
      'El discurso de divulgación científica adapta el conocimiento a un público no especializado: usa lenguaje más sencillo, ejemplos y analogías, a diferencia del discurso científico dirigido a especialistas.',
    source: 'original',
    version: 1,
    status: 'active',
  },
  {
    id: 'aau-teo-0010',
    institutions: ['UNSa'],
    subject: 'alfabetizacion',
    block: 'alfabetizacion_academica',
    topic: 'tipos_de_secuencia',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 2,
    stem: 'En una secuencia argumentativa, la **tesis** es:',
    choices: [
      {
        id: 'a',
        text: 'La postura o idea que el autor sostiene y busca defender.',
        correct: true,
      },
      {
        id: 'b',
        text: 'El conjunto de datos objetivos que no admiten discusión.',
        correct: false,
        feedback: 'Los datos objetivos pueden ser argumentos, pero la tesis es la postura defendida.',
      },
      {
        id: 'c',
        text: 'La secuencia de hechos narrados en orden cronológico.',
        correct: false,
        feedback: 'Eso pertenece a la narración, no a la argumentación.',
      },
      {
        id: 'd',
        text: 'La descripción detallada del tema que se trata.',
        correct: false,
        feedback: 'Describir el tema no equivale a fijar una postura (tesis).',
      },
    ],
    explanation:
      'La tesis es la afirmación central que el autor defiende en un texto argumentativo. Los argumentos son las razones que la sostienen.',
    source: 'original',
    version: 1,
    status: 'active',
  },
  {
    id: 'aau-teo-0011',
    institutions: ['UNSa'],
    subject: 'alfabetizacion',
    block: 'alfabetizacion_academica',
    topic: 'hecho_y_opinion',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 2,
    stem: '¿Cuál de estos enunciados corresponde a una **opinión** y no a un hecho?',
    choices: [
      {
        id: 'a',
        text: 'La contaminación del aire es el problema más grave de la ciudad.',
        correct: true,
      },
      {
        id: 'b',
        text: 'La ciudad registró un aumento de partículas en el aire.',
        correct: false,
        feedback: 'Ese es un dato verificable: un hecho.',
      },
      {
        id: 'c',
        text: 'El municipio midió la calidad del aire durante marzo.',
        correct: false,
        feedback: 'Es una acción constatable: un hecho.',
      },
      {
        id: 'd',
        text: 'El informe se publicó en el sitio oficial.',
        correct: false,
        feedback: 'Es un dato comprobable: un hecho.',
      },
    ],
    explanation:
      'Una opinión expresa una valoración subjetiva ("el más grave"), que puede discutirse. Un hecho es verificable y no depende del punto de vista de quien lo enuncia.',
    source: 'original',
    version: 1,
    status: 'active',
  },
  {
    id: 'aau-teo-0012',
    institutions: ['UNSa'],
    subject: 'alfabetizacion',
    block: 'alfabetizacion_academica',
    topic: 'coherencia_y_cohesion',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'baja',
    difficulty: 2,
    stem: 'Repetir una palabra clave o usar un sinónimo a lo largo del texto es un recurso de cohesión:',
    choices: [
      {
        id: 'a',
        text: 'Léxica.',
        correct: true,
      },
      {
        id: 'b',
        text: 'Gramatical.',
        correct: false,
        feedback: 'La cohesión gramatical usa pronombres, elipsis y conectores, no repetición léxica.',
      },
      {
        id: 'c',
        text: 'Fonética.',
        correct: false,
        feedback: 'La cohesión no se clasifica como fonética.',
      },
      {
        id: 'd',
        text: 'Paratextual.',
        correct: false,
        feedback: 'El paratexto rodea al texto; no es un mecanismo de cohesión interno.',
      },
    ],
    explanation:
      'La cohesión léxica se logra por repetición de palabras, sinonimia, hiperonimia o cadenas léxicas. La cohesión gramatical, en cambio, usa referencia, elipsis y conectores.',
    source: 'original',
    version: 1,
    status: 'active',
  },
];
