import type { Formula } from '../../../../types/content';

// Formulario: fórmulas clave con sus variables y —lo más importante para el
// examen— las relaciones de proporcionalidad directa/inversa entre variables.
export const formulas: Formula[] = [
  // ---------------- Química ----------------
  {
    id: 'for-ph',
    subject: 'quimica',
    name: 'pH',
    latex: 'pH = -\\log[H^+]',
    variables: [
      { symbol: 'pH', name: 'acidez', unit: '—' },
      { symbol: '[H⁺]', name: 'concentración de protones', unit: 'mol/L' },
    ],
    relations: [
      { a: 'pH', b: '[H⁺]', kind: 'inversa', note: 'escala logarítmica: a más H⁺, menor pH' },
    ],
  },
  {
    id: 'for-henderson',
    subject: 'quimica',
    name: 'Henderson-Hasselbalch (buffer)',
    latex: 'pH = pK_a + \\log\\dfrac{[\\text{base}]}{[\\text{ácido}]}',
    variables: [
      { symbol: 'pH', name: 'pH del buffer', unit: '—' },
      { symbol: 'pKa', name: 'fuerza del ácido', unit: '—' },
      { symbol: '[base]/[ácido]', name: 'relación conjugada', unit: '—' },
    ],
    relations: [
      { a: 'pH', b: '[base]/[ácido]', kind: 'directa', note: 'si relación = 1, pH = pKa' },
    ],
  },
  {
    id: 'for-molaridad',
    subject: 'quimica',
    name: 'Molaridad',
    latex: 'M = \\dfrac{n}{V}',
    variables: [
      { symbol: 'M', name: 'molaridad', unit: 'mol/L' },
      { symbol: 'n', name: 'moles de soluto', unit: 'mol' },
      { symbol: 'V', name: 'volumen de solución', unit: 'L' },
    ],
    relations: [
      { a: 'M', b: 'n', kind: 'directa', hold: 'V' },
      { a: 'M', b: 'V', kind: 'inversa', hold: 'n' },
    ],
  },
  {
    id: 'for-dilucion',
    subject: 'quimica',
    name: 'Dilución',
    latex: 'C_1 \\cdot V_1 = C_2 \\cdot V_2',
    variables: [
      { symbol: 'C', name: 'concentración', unit: 'mol/L' },
      { symbol: 'V', name: 'volumen', unit: 'L' },
    ],
    relations: [
      { a: 'C', b: 'V', kind: 'inversa', note: 'los moles de soluto se conservan' },
    ],
  },
  {
    id: 'for-gases',
    subject: 'quimica',
    name: 'Ley general de los gases',
    latex: 'P \\cdot V = n \\cdot R \\cdot T',
    variables: [
      { symbol: 'P', name: 'presión', unit: 'atm' },
      { symbol: 'V', name: 'volumen', unit: 'L' },
      { symbol: 'T', name: 'temperatura', unit: 'K' },
      { symbol: 'n', name: 'moles', unit: 'mol' },
    ],
    relations: [
      { a: 'P', b: 'V', kind: 'inversa', hold: 'T', note: 'Boyle' },
      { a: 'V', b: 'T', kind: 'directa', hold: 'P', note: 'Charles' },
      { a: 'P', b: 'T', kind: 'directa', hold: 'V', note: 'Gay-Lussac' },
    ],
  },
  // ---------------- Física ----------------
  {
    id: 'for-velocidad',
    subject: 'fisica',
    name: 'Velocidad (MRU)',
    latex: 'v = \\dfrac{\\Delta x}{\\Delta t}',
    variables: [
      { symbol: 'v', name: 'velocidad', unit: 'm/s' },
      { symbol: 'Δx', name: 'desplazamiento', unit: 'm' },
      { symbol: 'Δt', name: 'tiempo', unit: 's' },
    ],
    relations: [
      { a: 'v', b: 'Δx', kind: 'directa', hold: 'Δt' },
      { a: 'v', b: 'Δt', kind: 'inversa', hold: 'Δx' },
    ],
  },
  {
    id: 'for-mruv',
    subject: 'fisica',
    name: 'Velocidad final (MRUV)',
    latex: 'v_f = v_i + a \\cdot t',
    variables: [
      { symbol: 'vf', name: 'velocidad final', unit: 'm/s' },
      { symbol: 'vi', name: 'velocidad inicial', unit: 'm/s' },
      { symbol: 'a', name: 'aceleración', unit: 'm/s²' },
      { symbol: 't', name: 'tiempo', unit: 's' },
    ],
    relations: [
      { a: 'vf', b: 'a', kind: 'directa', hold: 't' },
      { a: 'vf', b: 't', kind: 'directa', hold: 'a' },
    ],
  },
  {
    id: 'for-newton2',
    subject: 'fisica',
    name: 'Segunda ley de Newton',
    latex: 'F = m \\cdot a',
    variables: [
      { symbol: 'F', name: 'fuerza', unit: 'N' },
      { symbol: 'm', name: 'masa', unit: 'kg' },
      { symbol: 'a', name: 'aceleración', unit: 'm/s²' },
    ],
    relations: [
      { a: 'F', b: 'm', kind: 'directa', hold: 'a' },
      { a: 'F', b: 'a', kind: 'directa', hold: 'm' },
      { a: 'a', b: 'm', kind: 'inversa', hold: 'F' },
    ],
  },
  {
    id: 'for-peso',
    subject: 'fisica',
    name: 'Peso',
    latex: 'P = m \\cdot g',
    variables: [
      { symbol: 'P', name: 'peso', unit: 'N' },
      { symbol: 'm', name: 'masa', unit: 'kg' },
      { symbol: 'g', name: 'gravedad', unit: 'm/s²' },
    ],
    relations: [{ a: 'P', b: 'm', kind: 'directa', hold: 'g' }],
  },
  {
    id: 'for-gravitacion',
    subject: 'fisica',
    name: 'Gravitación universal',
    latex: 'F = G\\,\\dfrac{m_1 \\cdot m_2}{d^2}',
    variables: [
      { symbol: 'F', name: 'fuerza gravitatoria', unit: 'N' },
      { symbol: 'm₁·m₂', name: 'producto de masas', unit: 'kg²' },
      { symbol: 'd', name: 'distancia', unit: 'm' },
    ],
    relations: [
      { a: 'F', b: 'm₁·m₂', kind: 'directa' },
      { a: 'F', b: 'd', kind: 'inversa', note: 'inversa al cuadrado (1/d²)' },
    ],
  },
  {
    id: 'for-trabajo',
    subject: 'fisica',
    name: 'Trabajo',
    latex: 'W = F \\cdot d \\cdot \\cos\\theta',
    variables: [
      { symbol: 'W', name: 'trabajo', unit: 'J' },
      { symbol: 'F', name: 'fuerza', unit: 'N' },
      { symbol: 'd', name: 'desplazamiento', unit: 'm' },
    ],
    relations: [
      { a: 'W', b: 'F', kind: 'directa', hold: 'd' },
      { a: 'W', b: 'd', kind: 'directa', hold: 'F' },
    ],
  },
  {
    id: 'for-ecinetica',
    subject: 'fisica',
    name: 'Energía cinética',
    latex: 'E_c = \\tfrac{1}{2}\\,m\\,v^2',
    variables: [
      { symbol: 'Ec', name: 'energía cinética', unit: 'J' },
      { symbol: 'm', name: 'masa', unit: 'kg' },
      { symbol: 'v', name: 'velocidad', unit: 'm/s' },
    ],
    relations: [
      { a: 'Ec', b: 'm', kind: 'directa', hold: 'v' },
      { a: 'Ec', b: 'v', kind: 'directa', note: 'con el cuadrado (v²)' },
    ],
  },
  {
    id: 'for-epotencial',
    subject: 'fisica',
    name: 'Energía potencial',
    latex: 'E_p = m \\cdot g \\cdot h',
    variables: [
      { symbol: 'Ep', name: 'energía potencial', unit: 'J' },
      { symbol: 'm', name: 'masa', unit: 'kg' },
      { symbol: 'h', name: 'altura', unit: 'm' },
    ],
    relations: [
      { a: 'Ep', b: 'h', kind: 'directa', hold: 'm' },
      { a: 'Ep', b: 'm', kind: 'directa', hold: 'h' },
    ],
  },
  {
    id: 'for-ohm',
    subject: 'fisica',
    name: 'Ley de Ohm',
    latex: 'V = I \\cdot R',
    variables: [
      { symbol: 'V', name: 'tensión', unit: 'V' },
      { symbol: 'I', name: 'corriente', unit: 'A' },
      { symbol: 'R', name: 'resistencia', unit: 'Ω' },
    ],
    relations: [
      { a: 'V', b: 'I', kind: 'directa', hold: 'R' },
      { a: 'V', b: 'R', kind: 'directa', hold: 'I' },
      { a: 'I', b: 'R', kind: 'inversa', hold: 'V' },
    ],
  },
  {
    id: 'for-presion',
    subject: 'fisica',
    name: 'Presión',
    latex: 'P = \\dfrac{F}{A}',
    variables: [
      { symbol: 'P', name: 'presión', unit: 'Pa' },
      { symbol: 'F', name: 'fuerza', unit: 'N' },
      { symbol: 'A', name: 'área', unit: 'm²' },
    ],
    relations: [
      { a: 'P', b: 'F', kind: 'directa', hold: 'A' },
      { a: 'P', b: 'A', kind: 'inversa', hold: 'F' },
    ],
  },
  {
    id: 'for-phidrostatica',
    subject: 'fisica',
    name: 'Presión hidrostática',
    latex: 'P = \\delta \\cdot g \\cdot h',
    variables: [
      { symbol: 'P', name: 'presión', unit: 'Pa' },
      { symbol: 'δ', name: 'densidad del líquido', unit: 'kg/m³' },
      { symbol: 'h', name: 'profundidad', unit: 'm' },
    ],
    relations: [
      { a: 'P', b: 'h', kind: 'directa', hold: 'δ' },
      { a: 'P', b: 'δ', kind: 'directa', hold: 'h' },
    ],
  },
  {
    id: 'for-densidad',
    subject: 'fisica',
    name: 'Densidad',
    latex: '\\delta = \\dfrac{m}{V}',
    variables: [
      { symbol: 'δ', name: 'densidad', unit: 'kg/m³' },
      { symbol: 'm', name: 'masa', unit: 'kg' },
      { symbol: 'V', name: 'volumen', unit: 'm³' },
    ],
    relations: [
      { a: 'δ', b: 'm', kind: 'directa', hold: 'V' },
      { a: 'δ', b: 'V', kind: 'inversa', hold: 'm' },
    ],
  },
  {
    id: 'for-caudal',
    subject: 'fisica',
    name: 'Caudal',
    latex: 'Q = v \\cdot A',
    variables: [
      { symbol: 'Q', name: 'caudal', unit: 'm³/s' },
      { symbol: 'v', name: 'velocidad', unit: 'm/s' },
      { symbol: 'A', name: 'área', unit: 'm²' },
    ],
    relations: [
      { a: 'Q', b: 'v', kind: 'directa', hold: 'A' },
      { a: 'Q', b: 'A', kind: 'directa', hold: 'v' },
    ],
  },

  // ============ Química — anexo HQ / Quantum (soluciones, coligativas, gases) ============
  {
    id: 'for-masa-atomica',
    subject: 'quimica',
    name: 'Masa atómica promedio',
    latex: 'A = \\dfrac{\\sum A_i \\cdot x_i}{100}',
    variables: [
      { symbol: 'A', name: 'masa atómica promedio', unit: 'uma' },
      { symbol: 'Aᵢ', name: 'masa de cada isótopo', unit: 'uma' },
      { symbol: 'xᵢ', name: 'abundancia de cada isótopo', unit: '%' },
    ],
    relations: [{ a: 'A', b: 'xᵢ', kind: 'directa', note: 'promedio ponderado por abundancia' }],
  },
  {
    id: 'for-comp-porcentual',
    subject: 'quimica',
    name: 'Composición porcentual',
    latex: 'C\\% = \\dfrac{m_e}{m_T} \\cdot 100',
    variables: [
      { symbol: 'C%', name: 'porcentaje del elemento', unit: '%' },
      { symbol: 'mₑ', name: 'masa del elemento', unit: 'g' },
      { symbol: 'm_T', name: 'masa total del compuesto', unit: 'g' },
    ],
    relations: [
      { a: 'C%', b: 'mₑ', kind: 'directa', hold: 'm_T' },
      { a: 'C%', b: 'm_T', kind: 'inversa', hold: 'mₑ' },
    ],
  },
  {
    id: 'for-moles',
    subject: 'quimica',
    name: 'Número de moles',
    latex: 'n = \\dfrac{m}{PM}',
    variables: [
      { symbol: 'n', name: 'moles', unit: 'mol' },
      { symbol: 'm', name: 'masa', unit: 'g' },
      { symbol: 'PM', name: 'masa molar', unit: 'g/mol' },
    ],
    relations: [
      { a: 'n', b: 'm', kind: 'directa', hold: 'PM' },
      { a: 'n', b: 'PM', kind: 'inversa', hold: 'm' },
    ],
  },
  {
    id: 'for-normalidad',
    subject: 'quimica',
    name: 'Normalidad',
    latex: 'N = \\dfrac{n_{eq}}{V} = M \\cdot z',
    variables: [
      { symbol: 'N', name: 'normalidad', unit: 'eq/L' },
      { symbol: 'n_eq', name: 'equivalentes de soluto', unit: 'eq' },
      { symbol: 'V', name: 'volumen de solución', unit: 'L' },
      { symbol: 'M', name: 'molaridad', unit: 'mol/L' },
      { symbol: 'z', name: 'valencia / carga', unit: '—' },
    ],
    relations: [
      { a: 'N', b: 'n_eq', kind: 'directa', hold: 'V' },
      { a: 'N', b: 'M', kind: 'directa', hold: 'z' },
    ],
  },
  {
    id: 'for-equivalentes',
    subject: 'quimica',
    name: 'Equivalentes y peso equivalente',
    latex: 'n_{eq} = \\dfrac{m}{P_{eq}}, \\quad P_{eq} = \\dfrac{PM}{z}',
    variables: [
      { symbol: 'n_eq', name: 'número de equivalentes', unit: 'eq' },
      { symbol: 'P_eq', name: 'peso equivalente', unit: 'g/eq' },
      { symbol: 'PM', name: 'masa molar', unit: 'g/mol' },
      { symbol: 'z', name: 'valencia', unit: '—' },
    ],
    relations: [{ a: 'P_eq', b: 'z', kind: 'inversa', hold: 'PM' }],
  },
  {
    id: 'for-molalidad',
    subject: 'quimica',
    name: 'Molalidad',
    latex: 'm = \\dfrac{n_s}{kg_{solvente}}',
    variables: [
      { symbol: 'm', name: 'molalidad', unit: 'mol/kg' },
      { symbol: 'nₛ', name: 'moles de soluto', unit: 'mol' },
      { symbol: 'kg', name: 'masa del solvente', unit: 'kg' },
    ],
    relations: [
      { a: 'm', b: 'nₛ', kind: 'directa', hold: 'kg' },
      { a: 'm', b: 'kg', kind: 'inversa', hold: 'nₛ' },
    ],
  },
  {
    id: 'for-fraccion-molar',
    subject: 'quimica',
    name: 'Fracción molar',
    latex: 'X_s = \\dfrac{n_s}{n_T}',
    variables: [
      { symbol: 'Xₛ', name: 'fracción molar del soluto', unit: '—' },
      { symbol: 'nₛ', name: 'moles de soluto', unit: 'mol' },
      { symbol: 'n_T', name: 'moles totales', unit: 'mol' },
    ],
    relations: [{ a: 'Xₛ', b: 'nₛ', kind: 'directa', hold: 'n_T' }],
  },
  {
    id: 'for-ppm',
    subject: 'quimica',
    name: 'Partes por millón',
    latex: 'ppm = \\dfrac{m_s}{m_T} \\cdot 10^6',
    variables: [
      { symbol: 'ppm', name: 'partes por millón', unit: 'mg/kg' },
      { symbol: 'mₛ', name: 'masa de soluto', unit: 'g' },
      { symbol: 'm_T', name: 'masa total', unit: 'g' },
    ],
    relations: [{ a: 'ppm', b: 'mₛ', kind: 'directa', hold: 'm_T' }],
  },
  {
    id: 'for-mezclas',
    subject: 'quimica',
    name: 'Mezcla de soluciones',
    latex: 'M_1 V_1 + M_2 V_2 = M_T \\, V_T',
    variables: [
      { symbol: 'M', name: 'molaridad de cada solución', unit: 'mol/L' },
      { symbol: 'V', name: 'volumen de cada solución', unit: 'L' },
      { symbol: 'M_T, V_T', name: 'molaridad y volumen finales', unit: '—' },
    ],
  },
  {
    id: 'for-presion-vapor',
    subject: 'quimica',
    name: 'Presión de vapor (Raoult)',
    latex: 'P_v = P^\\circ_v \\cdot X_{solvente}',
    variables: [
      { symbol: 'P_v', name: 'presión de vapor de la solución', unit: 'atm' },
      { symbol: 'P°_v', name: 'presión de vapor del solvente puro', unit: 'atm' },
      { symbol: 'X', name: 'fracción molar del solvente', unit: '—' },
    ],
    relations: [{ a: 'P_v', b: 'X', kind: 'directa', note: 'Ley de Raoult' }],
  },
  {
    id: 'for-ebulloscopico',
    subject: 'quimica',
    name: 'Aumento ebulloscópico',
    latex: '\\Delta T_b = n \\cdot K_b \\cdot m',
    variables: [
      { symbol: 'ΔT_b', name: 'aumento del punto de ebullición', unit: '°C' },
      { symbol: 'n', name: 'número de partículas (i)', unit: '—' },
      { symbol: 'K_b', name: 'constante ebulloscópica', unit: '°C·kg/mol' },
      { symbol: 'm', name: 'molalidad', unit: 'mol/kg' },
    ],
    relations: [{ a: 'ΔT_b', b: 'm', kind: 'directa', note: 'propiedad coligativa' }],
  },
  {
    id: 'for-crioscopico',
    subject: 'quimica',
    name: 'Descenso crioscópico',
    latex: '\\Delta T_c = n \\cdot K_c \\cdot m',
    variables: [
      { symbol: 'ΔT_c', name: 'descenso del punto de congelación', unit: '°C' },
      { symbol: 'n', name: 'número de partículas (i)', unit: '—' },
      { symbol: 'K_c', name: 'constante crioscópica', unit: '°C·kg/mol' },
      { symbol: 'm', name: 'molalidad', unit: 'mol/kg' },
    ],
    relations: [{ a: 'ΔT_c', b: 'm', kind: 'directa', note: 'propiedad coligativa' }],
  },
  {
    id: 'for-osmotica',
    subject: 'quimica',
    name: 'Presión osmótica',
    latex: '\\pi = n \\cdot M \\cdot R \\cdot T',
    variables: [
      { symbol: 'π', name: 'presión osmótica', unit: 'atm' },
      { symbol: 'n', name: 'número de partículas (i)', unit: '—' },
      { symbol: 'M', name: 'molaridad', unit: 'mol/L' },
      { symbol: 'R', name: 'constante de los gases', unit: '0,082 atm·L/mol·K' },
      { symbol: 'T', name: 'temperatura absoluta', unit: 'K' },
    ],
    relations: [
      { a: 'π', b: 'M', kind: 'directa', hold: 'T' },
      { a: 'π', b: 'T', kind: 'directa', hold: 'M' },
    ],
  },
  {
    id: 'for-poh',
    subject: 'quimica',
    name: 'pOH y producto iónico del agua',
    latex: 'pOH = -\\log[OH^-], \\quad pH + pOH = 14',
    variables: [
      { symbol: 'pOH', name: 'basicidad', unit: '—' },
      { symbol: '[OH⁻]', name: 'concentración de hidroxilos', unit: 'mol/L' },
      { symbol: 'pH', name: 'acidez', unit: '—' },
    ],
    relations: [{ a: 'pOH', b: '[OH⁻]', kind: 'inversa', note: 'escala logarítmica' }],
  },
  {
    id: 'for-ka',
    subject: 'quimica',
    name: 'Constante de equilibrio ácido (Ka)',
    latex: 'K_a = \\dfrac{x^2}{C_0 - x}',
    variables: [
      { symbol: 'Ka', name: 'constante de acidez', unit: '—' },
      { symbol: 'x', name: 'concentración disociada [H⁺]', unit: 'mol/L' },
      { symbol: 'C₀', name: 'concentración inicial del ácido', unit: 'mol/L' },
    ],
    relations: [{ a: 'x', b: 'Ka', kind: 'directa', note: 'a mayor Ka, ácido más fuerte' }],
  },
  {
    id: 'for-presion-parcial',
    subject: 'quimica',
    name: 'Presión parcial (Dalton)',
    latex: 'P_i = X_i \\cdot P_T',
    variables: [
      { symbol: 'P_i', name: 'presión parcial del gas', unit: 'atm' },
      { symbol: 'X_i', name: 'fracción molar del gas', unit: '—' },
      { symbol: 'P_T', name: 'presión total', unit: 'atm' },
    ],
    relations: [{ a: 'P_i', b: 'X_i', kind: 'directa', hold: 'P_T' }],
  },
  {
    id: 'for-graham',
    subject: 'quimica',
    name: 'Ley de difusión de Graham',
    latex: '\\dfrac{v_1}{v_2} = \\sqrt{\\dfrac{PM_2}{PM_1}}',
    variables: [
      { symbol: 'v', name: 'velocidad de difusión', unit: 'm/s' },
      { symbol: 'PM', name: 'masa molar', unit: 'g/mol' },
    ],
    relations: [{ a: 'v', b: 'PM', kind: 'inversa', note: 'difunde más rápido el gas más liviano' }],
  },

  // ============ Física — cinemática, dinámica, fluidos, electricidad, gases ============
  {
    id: 'for-aceleracion',
    subject: 'fisica',
    name: 'Aceleración (MRUV)',
    latex: 'a = \\dfrac{v_f - v_0}{t}',
    variables: [
      { symbol: 'a', name: 'aceleración', unit: 'm/s²' },
      { symbol: 'v_f', name: 'velocidad final', unit: 'm/s' },
      { symbol: 'v₀', name: 'velocidad inicial', unit: 'm/s' },
      { symbol: 't', name: 'tiempo', unit: 's' },
    ],
    relations: [{ a: 'a', b: 't', kind: 'inversa', note: 'para un mismo Δv' }],
  },
  {
    id: 'for-posicion-mruv',
    subject: 'fisica',
    name: 'Posición en MRUV',
    latex: 'd = v_0\\,t + \\tfrac{1}{2}\\,a\\,t^2',
    variables: [
      { symbol: 'd', name: 'distancia', unit: 'm' },
      { symbol: 'v₀', name: 'velocidad inicial', unit: 'm/s' },
      { symbol: 'a', name: 'aceleración', unit: 'm/s²' },
      { symbol: 't', name: 'tiempo', unit: 's' },
    ],
    relations: [{ a: 'd', b: 't', kind: 'directa', note: 'crece con el cuadrado del tiempo' }],
  },
  {
    id: 'for-torricelli',
    subject: 'fisica',
    name: 'Ecuación de Torricelli',
    latex: 'v_f^{\\,2} = v_0^{\\,2} + 2\\,a\\,d',
    variables: [
      { symbol: 'v_f', name: 'velocidad final', unit: 'm/s' },
      { symbol: 'v₀', name: 'velocidad inicial', unit: 'm/s' },
      { symbol: 'a', name: 'aceleración', unit: 'm/s²' },
      { symbol: 'd', name: 'distancia', unit: 'm' },
    ],
    relations: [{ a: 'v_f', b: 'd', kind: 'directa', note: 'no depende del tiempo' }],
  },
  {
    id: 'for-vmedia',
    subject: 'fisica',
    name: 'Velocidad media',
    latex: 'v_{media} = \\dfrac{d_{total}}{t_{total}}',
    variables: [
      { symbol: 'v_media', name: 'velocidad media', unit: 'm/s' },
      { symbol: 'd_total', name: 'distancia total', unit: 'm' },
      { symbol: 't_total', name: 'tiempo total', unit: 's' },
    ],
    relations: [{ a: 'v_media', b: 't_total', kind: 'inversa', hold: 'd_total' }],
  },
  {
    id: 'for-potencia',
    subject: 'fisica',
    name: 'Potencia mecánica',
    latex: 'Pot = \\dfrac{W}{t} = F \\cdot v',
    variables: [
      { symbol: 'Pot', name: 'potencia', unit: 'W' },
      { symbol: 'W', name: 'trabajo', unit: 'J' },
      { symbol: 't', name: 'tiempo', unit: 's' },
      { symbol: 'F', name: 'fuerza', unit: 'N' },
      { symbol: 'v', name: 'velocidad', unit: 'm/s' },
    ],
    relations: [
      { a: 'Pot', b: 'W', kind: 'directa', hold: 't' },
      { a: 'Pot', b: 't', kind: 'inversa', hold: 'W' },
    ],
  },
  {
    id: 'for-emecanica',
    subject: 'fisica',
    name: 'Energía mecánica',
    latex: 'E_m = E_c + E_p',
    variables: [
      { symbol: 'E_m', name: 'energía mecánica', unit: 'J' },
      { symbol: 'E_c', name: 'energía cinética', unit: 'J' },
      { symbol: 'E_p', name: 'energía potencial', unit: 'J' },
    ],
    relations: [{ a: 'E_m', b: 'E_c', kind: 'directa', note: 'se conserva con fuerzas conservativas' }],
  },
  {
    id: 'for-momento',
    subject: 'fisica',
    name: 'Cantidad de movimiento',
    latex: 'p = m \\cdot v',
    variables: [
      { symbol: 'p', name: 'cantidad de movimiento', unit: 'kg·m/s' },
      { symbol: 'm', name: 'masa', unit: 'kg' },
      { symbol: 'v', name: 'velocidad', unit: 'm/s' },
    ],
    relations: [
      { a: 'p', b: 'v', kind: 'directa', hold: 'm' },
      { a: 'p', b: 'm', kind: 'directa', hold: 'v' },
    ],
  },
  {
    id: 'for-plano-inclinado',
    subject: 'fisica',
    name: 'Aceleración en plano inclinado',
    latex: 'a = g \\cdot \\sin\\alpha',
    variables: [
      { symbol: 'a', name: 'aceleración', unit: 'm/s²' },
      { symbol: 'g', name: 'gravedad', unit: 'm/s²' },
      { symbol: 'α', name: 'ángulo de inclinación', unit: '°' },
    ],
    relations: [{ a: 'a', b: 'α', kind: 'directa', note: 'sin rozamiento' }],
  },
  {
    id: 'for-empuje',
    subject: 'fisica',
    name: 'Empuje (Arquímedes)',
    latex: 'E = \\delta_{fluido} \\cdot V_{sum} \\cdot g',
    variables: [
      { symbol: 'E', name: 'empuje', unit: 'N' },
      { symbol: 'δ', name: 'densidad del fluido', unit: 'kg/m³' },
      { symbol: 'V_sum', name: 'volumen sumergido', unit: 'm³' },
      { symbol: 'g', name: 'gravedad', unit: 'm/s²' },
    ],
    relations: [
      { a: 'E', b: 'V_sum', kind: 'directa', hold: 'δ' },
      { a: 'E', b: 'δ', kind: 'directa', hold: 'V_sum' },
    ],
  },
  {
    id: 'for-presion-abs',
    subject: 'fisica',
    name: 'Presión absoluta',
    latex: 'P_{abs} = P_{atm} + P_h',
    variables: [
      { symbol: 'P_abs', name: 'presión absoluta (total)', unit: 'Pa' },
      { symbol: 'P_atm', name: 'presión atmosférica', unit: 'Pa' },
      { symbol: 'P_h', name: 'presión hidrostática (manométrica)', unit: 'Pa' },
    ],
    relations: [{ a: 'P_abs', b: 'P_h', kind: 'directa', hold: 'P_atm' }],
  },
  {
    id: 'for-pascal',
    subject: 'fisica',
    name: 'Prensa hidráulica (Pascal)',
    latex: '\\dfrac{F_1}{A_1} = \\dfrac{F_2}{A_2}',
    variables: [
      { symbol: 'F', name: 'fuerza en cada émbolo', unit: 'N' },
      { symbol: 'A', name: 'área de cada émbolo', unit: 'm²' },
    ],
    relations: [{ a: 'F₂', b: 'A₂', kind: 'directa', note: 'multiplica la fuerza según el área' }],
  },
  {
    id: 'for-continuidad',
    subject: 'fisica',
    name: 'Ecuación de continuidad',
    latex: 'v_1 A_1 = v_2 A_2',
    variables: [
      { symbol: 'v', name: 'velocidad del fluido', unit: 'm/s' },
      { symbol: 'A', name: 'área de la sección', unit: 'm²' },
    ],
    relations: [{ a: 'v', b: 'A', kind: 'inversa', note: 'a menor sección, mayor velocidad' }],
  },
  {
    id: 'for-bernoulli',
    subject: 'fisica',
    name: 'Presión cinética (Bernoulli)',
    latex: 'P_c = \\tfrac{1}{2}\\,\\delta\\,v^2',
    variables: [
      { symbol: 'P_c', name: 'presión cinética', unit: 'Pa' },
      { symbol: 'δ', name: 'densidad del fluido', unit: 'kg/m³' },
      { symbol: 'v', name: 'velocidad', unit: 'm/s' },
    ],
    relations: [{ a: 'P_c', b: 'v', kind: 'directa', note: 'crece con el cuadrado de la velocidad' }],
  },
  {
    id: 'for-coulomb',
    subject: 'fisica',
    name: 'Ley de Coulomb',
    latex: 'F_{el} = \\dfrac{k\\,q_1\\,q_2}{d^2}',
    variables: [
      { symbol: 'F_el', name: 'fuerza eléctrica', unit: 'N' },
      { symbol: 'k', name: 'constante de Coulomb', unit: '9·10⁹ N·m²/C²' },
      { symbol: 'q₁·q₂', name: 'producto de cargas', unit: 'C²' },
      { symbol: 'd', name: 'distancia', unit: 'm' },
    ],
    relations: [
      { a: 'F_el', b: 'q₁·q₂', kind: 'directa', hold: 'd' },
      { a: 'F_el', b: 'd', kind: 'inversa', note: 'inversa al cuadrado de la distancia' },
    ],
  },
  {
    id: 'for-campo-electrico',
    subject: 'fisica',
    name: 'Campo eléctrico',
    latex: 'E = \\dfrac{F_{el}}{q} = \\dfrac{k\\,q}{d^2}',
    variables: [
      { symbol: 'E', name: 'campo eléctrico', unit: 'N/C' },
      { symbol: 'F_el', name: 'fuerza eléctrica', unit: 'N' },
      { symbol: 'q', name: 'carga', unit: 'C' },
      { symbol: 'd', name: 'distancia', unit: 'm' },
    ],
    relations: [{ a: 'E', b: 'd', kind: 'inversa', note: 'inversa al cuadrado' }],
  },
  {
    id: 'for-potencial-electrico',
    subject: 'fisica',
    name: 'Potencial eléctrico',
    latex: 'V = \\dfrac{k\\,q}{d}',
    variables: [
      { symbol: 'V', name: 'potencial eléctrico', unit: 'V' },
      { symbol: 'k', name: 'constante de Coulomb', unit: '9·10⁹' },
      { symbol: 'q', name: 'carga', unit: 'C' },
      { symbol: 'd', name: 'distancia', unit: 'm' },
    ],
    relations: [{ a: 'V', b: 'd', kind: 'inversa', hold: 'q' }],
  },
  {
    id: 'for-capacidad',
    subject: 'fisica',
    name: 'Capacidad de un condensador',
    latex: 'C = \\dfrac{q}{\\Delta V}',
    variables: [
      { symbol: 'C', name: 'capacidad', unit: 'F' },
      { symbol: 'q', name: 'carga almacenada', unit: 'C' },
      { symbol: 'ΔV', name: 'diferencia de potencial', unit: 'V' },
    ],
    relations: [
      { a: 'C', b: 'q', kind: 'directa', hold: 'ΔV' },
      { a: 'C', b: 'ΔV', kind: 'inversa', hold: 'q' },
    ],
  },
  {
    id: 'for-potencia-electrica',
    subject: 'fisica',
    name: 'Potencia eléctrica',
    latex: 'Pot = V \\cdot I = I^2 R = \\dfrac{V^2}{R}',
    variables: [
      { symbol: 'Pot', name: 'potencia', unit: 'W' },
      { symbol: 'V', name: 'tensión', unit: 'V' },
      { symbol: 'I', name: 'intensidad', unit: 'A' },
      { symbol: 'R', name: 'resistencia', unit: 'Ω' },
    ],
    relations: [{ a: 'Pot', b: 'I', kind: 'directa', hold: 'V' }],
  },
  {
    id: 'for-resistencias',
    subject: 'fisica',
    name: 'Resistencias en serie y paralelo',
    latex: 'R_s = R_1 + R_2, \\quad \\dfrac{1}{R_p} = \\dfrac{1}{R_1} + \\dfrac{1}{R_2}',
    variables: [
      { symbol: 'R_s', name: 'resistencia en serie', unit: 'Ω' },
      { symbol: 'R_p', name: 'resistencia en paralelo', unit: 'Ω' },
      { symbol: 'R₁, R₂', name: 'resistencias', unit: 'Ω' },
    ],
    relations: [{ a: 'R_s', b: 'R₁, R₂', kind: 'directa', note: 'en serie se suman; en paralelo baja' }],
  },
  {
    id: 'for-resistividad',
    subject: 'fisica',
    name: 'Resistencia de un conductor',
    latex: 'R = \\rho \\cdot \\dfrac{l}{S}',
    variables: [
      { symbol: 'R', name: 'resistencia', unit: 'Ω' },
      { symbol: 'ρ', name: 'resistividad', unit: 'Ω·m' },
      { symbol: 'l', name: 'longitud', unit: 'm' },
      { symbol: 'S', name: 'sección', unit: 'm²' },
    ],
    relations: [
      { a: 'R', b: 'l', kind: 'directa', hold: 'S' },
      { a: 'R', b: 'S', kind: 'inversa', hold: 'l' },
    ],
  },
  {
    id: 'for-fick',
    subject: 'fisica',
    name: 'Ley de Fick (difusión por membrana)',
    latex: 'J = \\dfrac{D \\cdot A \\cdot (C_1 - C_2)}{L}',
    variables: [
      { symbol: 'J', name: 'flujo de difusión', unit: 'mol/s' },
      { symbol: 'D', name: 'coeficiente de difusión', unit: 'm²/s' },
      { symbol: 'A', name: 'área de la membrana', unit: 'm²' },
      { symbol: 'C₁−C₂', name: 'gradiente de concentración', unit: 'mol/m³' },
      { symbol: 'L', name: 'espesor de la membrana', unit: 'm' },
    ],
    relations: [
      { a: 'J', b: 'C₁−C₂', kind: 'directa', note: 'a mayor gradiente, más transporte' },
      { a: 'J', b: 'L', kind: 'inversa', note: 'membrana más gruesa difunde menos' },
    ],
  },
  {
    id: 'for-teoria-cinetica',
    subject: 'fisica',
    name: 'Energía cinética molecular (gases)',
    latex: 'E_c = \\tfrac{3}{2}\\,k\\,T',
    variables: [
      { symbol: 'E_c', name: 'energía cinética media', unit: 'J' },
      { symbol: 'k', name: 'constante de Boltzmann', unit: '1,38·10⁻²³ J/K' },
      { symbol: 'T', name: 'temperatura absoluta', unit: 'K' },
    ],
    relations: [{ a: 'E_c', b: 'T', kind: 'directa', note: 'la temperatura mide la energía cinética' }],
  },
  {
    id: 'for-temp-absoluta',
    subject: 'fisica',
    name: 'Temperatura absoluta',
    latex: 'T(K) = t(^\\circ C) + 273',
    variables: [
      { symbol: 'T', name: 'temperatura absoluta', unit: 'K' },
      { symbol: 't', name: 'temperatura', unit: '°C' },
    ],
    relations: [{ a: 'T', b: 't', kind: 'directa' }],
  },

  // ============ Matemática — herramientas para física/química ============
  {
    id: 'for-trigonometria',
    subject: 'matematica',
    name: 'Razones trigonométricas',
    latex: '\\sin\\theta = \\dfrac{CO}{H},\\ \\cos\\theta = \\dfrac{CA}{H},\\ \\tan\\theta = \\dfrac{CO}{CA}',
    variables: [
      { symbol: 'CO', name: 'cateto opuesto', unit: '—' },
      { symbol: 'CA', name: 'cateto adyacente', unit: '—' },
      { symbol: 'H', name: 'hipotenusa', unit: '—' },
    ],
  },
  {
    id: 'for-pitagoras',
    subject: 'matematica',
    name: 'Teorema de Pitágoras',
    latex: 'H^2 = CA^2 + CO^2',
    variables: [
      { symbol: 'H', name: 'hipotenusa', unit: '—' },
      { symbol: 'CA, CO', name: 'catetos', unit: '—' },
    ],
  },
  {
    id: 'for-teorema-coseno',
    subject: 'matematica',
    name: 'Teorema del coseno',
    latex: 'a^2 = b^2 + c^2 - 2\\,b\\,c\\,\\cos\\alpha',
    variables: [
      { symbol: 'a, b, c', name: 'lados del triángulo', unit: '—' },
      { symbol: 'α', name: 'ángulo opuesto al lado a', unit: '°' },
    ],
  },
  {
    id: 'for-funcion-lineal',
    subject: 'matematica',
    name: 'Función lineal',
    latex: 'y = m\\,x + n, \\quad m = \\dfrac{y_2 - y_1}{x_2 - x_1}',
    variables: [
      { symbol: 'm', name: 'pendiente', unit: '—' },
      { symbol: 'n', name: 'ordenada al origen', unit: '—' },
    ],
    relations: [{ a: 'y', b: 'x', kind: 'directa', note: 'si m>0 crece; si m<0 decrece' }],
  },
  {
    id: 'for-funcion-cuadratica',
    subject: 'matematica',
    name: 'Función cuadrática',
    latex: 'x = \\dfrac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}, \\quad x_v = \\dfrac{-b}{2a}',
    variables: [
      { symbol: 'a, b, c', name: 'coeficientes', unit: '—' },
      { symbol: 'x', name: 'raíces', unit: '—' },
      { symbol: 'x_v', name: 'abscisa del vértice', unit: '—' },
    ],
  },
  {
    id: 'for-logaritmo',
    subject: 'matematica',
    name: 'Logaritmo',
    latex: '\\log_a c = b \\iff a^b = c',
    variables: [
      { symbol: 'a', name: 'base', unit: '—' },
      { symbol: 'c', name: 'argumento', unit: '—' },
      { symbol: 'b', name: 'logaritmo', unit: '—' },
    ],
  },
];

export const formulaById = new Map(formulas.map((f) => [f.id, f]));
