import type { Item } from '../../../../../types/content';
import { mc } from '../_build';

const S = 'historia' as const;

export const items: Item[] = [
  mc({
    id: 'gna-his-ind-1',
    subject: S,
    block: 'independencia_y_anarquia',
    topic: 'revolucion_de_mayo',
    difficulty: 1,
    stem: 'La Primera Junta de Gobierno se conformó el:',
    choices: [
      { t: '25 de mayo de 1810.', ok: true },
      { t: '9 de julio de 1816.' },
      { t: '20 de junio de 1820.' },
      { t: '25 de mayo de 1853.' },
    ],
    explanation:
      'La Primera Junta se formó el 25 de mayo de 1810. El 9 de julio de 1816 se declaró la Independencia.',
  }),
  mc({
    id: 'gna-his-ind-2',
    subject: S,
    block: 'independencia_y_anarquia',
    topic: 'congreso_de_tucuman',
    difficulty: 2,
    stem: 'En el Congreso de Tucumán de 1816 se declaró:',
    choices: [
      { t: 'la Independencia de las Provincias Unidas.', ok: true },
      { t: 'la primera Constitución Nacional.' },
      { t: 'la caída de Juan Manuel de Rosas.' },
      { t: 'la federalización de Buenos Aires.' },
    ],
    explanation:
      'El 9 de julio de 1816 el Congreso de Tucumán declaró la Independencia. La Constitución llegaría en 1853.',
  }),
  mc({
    id: 'gna-his-org-1',
    subject: S,
    block: 'rosas_y_organizacion_nacional',
    topic: 'constitucion_1853',
    difficulty: 2,
    stem: 'La Constitución Nacional Argentina fue sancionada por primera vez en el año:',
    choices: [
      { t: '1853.', ok: true },
      { t: '1810.' },
      { t: '1816.' },
      { t: '1880.' },
    ],
    explanation:
      'Tras la caída de Rosas (1852), el Congreso Constituyente sancionó la Constitución en 1853.',
  }),
  mc({
    id: 'gna-his-org-2',
    subject: S,
    block: 'rosas_y_organizacion_nacional',
    topic: 'caida_de_rosas',
    difficulty: 2,
    stem: 'Juan Manuel de Rosas fue derrotado en la batalla de Caseros (1852) por las fuerzas de:',
    choices: [
      { t: 'Justo José de Urquiza.', ok: true },
      { t: 'Bartolomé Mitre.' },
      { t: 'Domingo F. Sarmiento.' },
      { t: 'Julio A. Roca.' },
    ],
    explanation:
      'Urquiza encabezó el Ejército Grande que venció a Rosas en Caseros, abriendo la etapa de organización nacional.',
  }),
  mc({
    id: 'gna-his-est-1',
    subject: S,
    block: 'estado_nacional',
    topic: 'ley_saenz_pena',
    difficulty: 3,
    stem: 'La Ley Sáenz Peña (1912) estableció el voto:',
    choices: [
      { t: 'universal, secreto y obligatorio (masculino).', ok: true },
      { t: 'universal, incluyendo a las mujeres.' },
      { t: 'calificado según la renta del votante.' },
      { t: 'optativo y a viva voz.' },
    ],
    explanation:
      'La Ley 8871 instauró el sufragio universal (masculino), secreto y obligatorio. El voto femenino llegó en 1947.',
  }),
  mc({
    id: 'gna-his-rad-1',
    subject: S,
    block: 'radicales_y_conservadores',
    topic: 'primer_presidente_radical',
    difficulty: 2,
    stem: 'El primer presidente argentino elegido con la Ley Sáenz Peña, en 1916, fue:',
    choices: [
      { t: 'Hipólito Yrigoyen.', ok: true },
      { t: 'Marcelo T. de Alvear.' },
      { t: 'Juan D. Perón.' },
      { t: 'Roque Sáenz Peña.' },
    ],
    explanation:
      'Hipólito Yrigoyen (UCR) asumió en 1916, primer presidente electo por voto universal, secreto y obligatorio.',
  }),
  mc({
    id: 'gna-his-per-1',
    subject: S,
    block: 'peronismo_y_posperonismo',
    topic: 'voto_femenino',
    difficulty: 2,
    stem: 'El voto femenino se estableció en Argentina en 1947, durante la presidencia de:',
    choices: [
      { t: 'Juan Domingo Perón.', ok: true },
      { t: 'Hipólito Yrigoyen.' },
      { t: 'Arturo Frondizi.' },
      { t: 'Juan Carlos Onganía.' },
    ],
    explanation:
      'La Ley 13.010 (1947), impulsada durante el primer gobierno de Perón, reconoció los derechos políticos de la mujer.',
  }),
  mc({
    id: 'gna-his-dem-1',
    subject: S,
    block: 'proceso_y_democracia',
    topic: 'retorno_democratico',
    difficulty: 1,
    stem: 'La democracia se restableció en Argentina en 1983 con la presidencia de:',
    choices: [
      { t: 'Raúl Alfonsín.', ok: true },
      { t: 'Carlos Menem.' },
      { t: 'Fernando de la Rúa.' },
      { t: 'Arturo Illia.' },
    ],
    explanation:
      'Raúl Alfonsín (UCR) asumió el 10 de diciembre de 1983, tras el último gobierno militar.',
  }),

  // ---- Independencia y anarquía (1810-1829) ----
  mc({
    id: 'gna-his-ind-3',
    subject: S,
    block: 'independencia_y_anarquia',
    topic: 'asamblea_1813',
    difficulty: 3,
    stem: 'La Asamblea del Año XIII (1813) tomó, entre otras, la decisión de:',
    choices: [
      { t: 'aprobar el Himno y la libertad de vientres.', ok: true },
      { t: 'declarar la Independencia nacional.' },
      { t: 'sancionar la Constitución de 1853.' },
      { t: 'derrocar a Juan Manuel de Rosas.' },
    ],
    explanation:
      'La Asamblea del Año XIII aprobó el Himno, el escudo, la libertad de vientres y abolió títulos de nobleza, pero no declaró la Independencia (eso fue en 1816).',
  }),
  mc({
    id: 'gna-his-ind-4',
    subject: S,
    block: 'independencia_y_anarquia',
    topic: 'cruce_de_los_andes',
    difficulty: 2,
    stem: 'El general que organizó el Ejército de los Andes y cruzó la cordillera para liberar Chile y Perú fue:',
    choices: [
      { t: 'José de San Martín.', ok: true },
      { t: 'Manuel Belgrano.' },
      { t: 'Juan José Castelli.' },
      { t: 'Cornelio Saavedra.' },
    ],
    explanation:
      'José de San Martín formó el Ejército de los Andes en Cuyo y cruzó la cordillera en 1817 rumbo a Chile y luego Perú.',
  }),
  mc({
    id: 'gna-his-ind-5',
    subject: S,
    block: 'independencia_y_anarquia',
    topic: 'anarquia_1820',
    difficulty: 3,
    stem: 'El "año 20" (1820) se conoce como el año de la anarquía porque:',
    choices: [
      { t: 'cayó el poder central y se disolvió el Directorio.', ok: true },
      { t: 'se sancionó la Constitución unitaria.' },
      { t: 'asumió la primera presidencia constitucional.' },
      { t: 'terminó la guerra con el Brasil.' },
    ],
    explanation:
      'Tras la batalla de Cepeda (1820) se disolvieron el Directorio y el Congreso; las provincias quedaron sin poder central.',
  }),

  // ---- Rosas y organización nacional (1829-1880) ----
  mc({
    id: 'gna-his-org-3',
    subject: S,
    block: 'rosas_y_organizacion_nacional',
    topic: 'rosas_gobierno',
    difficulty: 2,
    stem: 'Juan Manuel de Rosas gobernó Buenos Aires como líder del partido:',
    choices: [
      { t: 'federal.', ok: true },
      { t: 'unitario.' },
      { t: 'radical.' },
      { t: 'conservador.' },
    ],
    explanation:
      'Rosas fue el principal referente de los federales; gobernó con la suma del poder público y el título de "Restaurador de las Leyes".',
  }),
  mc({
    id: 'gna-his-org-4',
    subject: S,
    block: 'rosas_y_organizacion_nacional',
    topic: 'presidencia_mitre',
    difficulty: 3,
    stem: 'El primer presidente de la Nación tras la unificación (1862) fue:',
    choices: [
      { t: 'Bartolomé Mitre.', ok: true },
      { t: 'Justo José de Urquiza.' },
      { t: 'Domingo F. Sarmiento.' },
      { t: 'Nicolás Avellaneda.' },
    ],
    explanation:
      'Luego de Pavón (1861) y la unificación, Bartolomé Mitre fue el primer presidente del país unificado (1862-1868).',
  }),
  mc({
    id: 'gna-his-org-5',
    subject: S,
    block: 'rosas_y_organizacion_nacional',
    topic: 'presidencia_sarmiento',
    difficulty: 2,
    stem: 'Domingo F. Sarmiento es especialmente recordado por su política de:',
    choices: [
      { t: 'expansión de la educación pública.', ok: true },
      { t: 'nacionalización de los ferrocarriles.' },
      { t: 'estatización de la industria.' },
      { t: 'reforma agraria.' },
    ],
    explanation:
      'Sarmiento (1868-1874) impulsó fuertemente la educación pública, la creación de escuelas y la formación de maestros.',
  }),

  // ---- Consolidación del Estado nacional (1880-1916) ----
  mc({
    id: 'gna-his-est-2',
    subject: S,
    block: 'estado_nacional',
    topic: 'federalizacion_bsas',
    difficulty: 2,
    stem: 'En 1880, durante la presidencia de Julio A. Roca, la ciudad de Buenos Aires fue:',
    choices: [
      { t: 'federalizada como Capital de la Nación.', ok: true },
      { t: 'separada del territorio argentino.' },
      { t: 'convertida en provincia autónoma.' },
      { t: 'cedida al gobierno del Brasil.' },
    ],
    explanation:
      'En 1880 Buenos Aires fue federalizada y declarada Capital Federal, cerrando el conflicto entre la provincia y la Nación.',
  }),
  mc({
    id: 'gna-his-est-3',
    subject: S,
    block: 'estado_nacional',
    topic: 'ley_1420',
    difficulty: 3,
    stem: 'La Ley 1420 (1884) estableció que la educación primaria fuera:',
    choices: [
      { t: 'gratuita, obligatoria y laica.', ok: true },
      { t: 'paga y optativa.' },
      { t: 'exclusivamente religiosa.' },
      { t: 'reservada a los varones.' },
    ],
    explanation:
      'La Ley 1420 instauró la educación primaria común, gratuita, obligatoria y laica, base del sistema educativo argentino.',
  }),
  mc({
    id: 'gna-his-est-4',
    subject: S,
    block: 'estado_nacional',
    topic: 'inmigracion',
    difficulty: 2,
    stem: 'Entre 1880 y 1914 Argentina recibió una gran corriente de inmigrantes provenientes principalmente de:',
    choices: [
      { t: 'Europa, sobre todo Italia y España.', ok: true },
      { t: 'Asia, sobre todo China y Japón.' },
      { t: 'América del Norte.' },
      { t: 'Oceanía.' },
    ],
    explanation:
      'La inmigración masiva fue mayoritariamente europea, con predominio de italianos y españoles, transformando la sociedad argentina.',
  }),

  // ---- Radicales y conservadores (1916-1943) ----
  mc({
    id: 'gna-his-rad-2',
    subject: S,
    block: 'radicales_y_conservadores',
    topic: 'golpe_1930',
    difficulty: 2,
    stem: 'El primer golpe de Estado del siglo XX en Argentina (1930) derrocó a:',
    choices: [
      { t: 'Hipólito Yrigoyen.', ok: true },
      { t: 'Marcelo T. de Alvear.' },
      { t: 'Juan D. Perón.' },
      { t: 'Arturo Illia.' },
    ],
    explanation:
      'El 6 de septiembre de 1930 un golpe encabezado por José F. Uriburu derrocó a Yrigoyen en su segunda presidencia.',
  }),
  mc({
    id: 'gna-his-rad-3',
    subject: S,
    block: 'radicales_y_conservadores',
    topic: 'decada_infame',
    difficulty: 3,
    stem: 'La "Década Infame" (años 30) se caracterizó por:',
    choices: [
      { t: 'el fraude electoral y el Pacto Roca-Runciman.', ok: true },
      { t: 'el sufragio universal femenino.' },
      { t: 'la reforma agraria integral.' },
      { t: 'la nacionalización de los ferrocarriles.' },
    ],
    explanation:
      'La Década Infame combinó fraude electoral sistemático con acuerdos como el Pacto Roca-Runciman (1933) con Gran Bretaña.',
  }),

  // ---- Peronismo y posperonismo (1943-1976) ----
  mc({
    id: 'gna-his-per-2',
    subject: S,
    block: 'peronismo_y_posperonismo',
    topic: 'constitucion_1949',
    difficulty: 3,
    stem: 'La reforma constitucional de 1949, durante el primer peronismo, incorporó:',
    choices: [
      { t: 'la reelección presidencial y los derechos sociales.', ok: true },
      { t: 'la abolición del voto femenino.' },
      { t: 'el sistema parlamentario.' },
      { t: 'la eliminación del Poder Judicial.' },
    ],
    explanation:
      'La Constitución de 1949 habilitó la reelección presidencial e incorporó derechos del trabajador, la ancianidad y la familia. Fue derogada en 1956.',
  }),
  mc({
    id: 'gna-his-per-3',
    subject: S,
    block: 'peronismo_y_posperonismo',
    topic: 'revolucion_libertadora',
    difficulty: 2,
    stem: 'El golpe militar de 1955 que derrocó a Juan D. Perón se autodenominó:',
    choices: [
      { t: '"Revolución Libertadora".', ok: true },
      { t: '"Proceso de Reorganización Nacional".' },
      { t: '"Revolución Argentina".' },
      { t: '"Revolución del Parque".' },
    ],
    explanation:
      'La "Revolución Libertadora" (1955) derrocó a Perón. El "Proceso" fue en 1976 y la "Revolución Argentina" en 1966.',
  }),
  mc({
    id: 'gna-his-per-4',
    subject: S,
    block: 'peronismo_y_posperonismo',
    topic: 'revolucion_argentina',
    difficulty: 3,
    stem: 'La "Revolución Argentina" (1966), que derrocó a Arturo Illia, fue encabezada por:',
    choices: [
      { t: 'Juan Carlos Onganía.', ok: true },
      { t: 'Jorge R. Videla.' },
      { t: 'Pedro E. Aramburu.' },
      { t: 'Roberto M. Levingston.' },
    ],
    explanation:
      'El golpe de 1966 llevó al poder a Juan Carlos Onganía, iniciando la llamada "Revolución Argentina".',
  }),

  // ---- Proceso y democracia (1976-actualidad) ----
  mc({
    id: 'gna-his-dem-2',
    subject: S,
    block: 'proceso_y_democracia',
    topic: 'golpe_1976',
    difficulty: 1,
    stem: 'El último golpe de Estado en Argentina se produjo el:',
    choices: [
      { t: '24 de marzo de 1976.', ok: true },
      { t: '6 de septiembre de 1930.' },
      { t: '16 de septiembre de 1955.' },
      { t: '28 de junio de 1966.' },
    ],
    explanation:
      'El 24 de marzo de 1976 una junta militar derrocó a María Estela Martínez de Perón e inició el "Proceso de Reorganización Nacional".',
  }),
  mc({
    id: 'gna-his-dem-3',
    subject: S,
    block: 'proceso_y_democracia',
    topic: 'malvinas',
    difficulty: 2,
    stem: 'La Guerra de Malvinas contra el Reino Unido se desarrolló en el año:',
    choices: [
      { t: '1982.', ok: true },
      { t: '1978.' },
      { t: '1976.' },
      { t: '1989.' },
    ],
    explanation:
      'La Guerra de Malvinas ocurrió entre abril y junio de 1982, durante la presidencia de facto de Leopoldo Galtieri.',
  }),
  mc({
    id: 'gna-his-dem-4',
    subject: S,
    block: 'proceso_y_democracia',
    topic: 'juicio_juntas',
    difficulty: 3,
    stem: 'El Juicio a las Juntas Militares, que condenó a los responsables de la dictadura, se realizó en 1985 bajo la presidencia de:',
    choices: [
      { t: 'Raúl Alfonsín.', ok: true },
      { t: 'Carlos Menem.' },
      { t: 'Néstor Kirchner.' },
      { t: 'Fernando de la Rúa.' },
    ],
    explanation:
      'El Juicio a las Juntas (1985) se realizó durante el gobierno de Alfonsín; fue inédito en la región por juzgar a excomandantes en un tribunal civil.',
  }),
  mc({
    id: 'gna-his-dem-5',
    subject: S,
    block: 'proceso_y_democracia',
    topic: 'reforma_1994',
    difficulty: 3,
    stem: 'La última reforma de la Constitución Nacional se realizó en el año:',
    choices: [
      { t: '1994.', ok: true },
      { t: '1949.' },
      { t: '1983.' },
      { t: '2001.' },
    ],
    explanation:
      'La reforma de 1994 incorporó, entre otros, nuevos derechos y garantías, el Consejo de la Magistratura y la reelección presidencial por un período.',
  }),

  // ======== Tanda 2: Independencia y anarquía ========
  mc({
    id: 'gna-his-ind-6', subject: S, block: 'independencia_y_anarquia', topic: 'creacion_bandera', difficulty: 2,
    stem: 'La bandera argentina fue creada en 1812, a orillas del río Paraná, por:',
    choices: [{ t: 'Manuel Belgrano.', ok: true }, { t: 'José de San Martín.' }, { t: 'Cornelio Saavedra.' }, { t: 'Mariano Moreno.' }],
    explanation: 'Manuel Belgrano enarboló por primera vez la bandera en Rosario, el 27 de febrero de 1812.',
  }),
  mc({
    id: 'gna-his-ind-7', subject: S, block: 'independencia_y_anarquia', topic: 'san_lorenzo', difficulty: 3,
    stem: 'En el Combate de San Lorenzo (1813), San Martín tuvo su bautismo de fuego al frente del regimiento de:',
    choices: [{ t: 'Granaderos a Caballo.', ok: true }, { t: 'Patricios.' }, { t: 'Húsares.' }, { t: 'Blandengues.' }],
    explanation: 'San Martín creó y comandó el Regimiento de Granaderos a Caballo, que actuó en San Lorenzo en 1813.',
  }),
  mc({
    id: 'gna-his-ind-8', subject: S, block: 'independencia_y_anarquia', topic: 'primera_junta', difficulty: 2,
    stem: 'El presidente de la Primera Junta de Gobierno (1810) fue:',
    choices: [{ t: 'Cornelio Saavedra.', ok: true }, { t: 'Manuel Belgrano.' }, { t: 'Juan José Paso.' }, { t: 'Bernardino Rivadavia.' }],
    explanation: 'Cornelio Saavedra presidió la Primera Junta; Mariano Moreno y Juan José Paso fueron secretarios.',
  }),
  mc({
    id: 'gna-his-ind-9', subject: S, block: 'independencia_y_anarquia', topic: 'cepeda_1820', difficulty: 3,
    stem: 'La batalla de Cepeda de 1820 tuvo como consecuencia:',
    choices: [{ t: 'la disolución del poder central (Directorio y Congreso).', ok: true }, { t: 'la declaración de la Independencia.' }, { t: 'la sanción de la Constitución.' }, { t: 'la caída de Rosas.' }],
    explanation: 'En Cepeda (1820) las fuerzas federales derrotaron al Directorio, que se disolvió, dando inicio a la anarquía.',
  }),

  // ======== Tanda 2: Rosas y organización nacional ========
  mc({
    id: 'gna-his-org-6', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'bases_alberdi', difficulty: 3,
    stem: 'La obra "Bases y puntos de partida para la organización política", que inspiró la Constitución de 1853, fue escrita por:',
    choices: [{ t: 'Juan Bautista Alberdi.', ok: true }, { t: 'Domingo F. Sarmiento.' }, { t: 'Bartolomé Mitre.' }, { t: 'Juan Manuel de Rosas.' }],
    explanation: 'Alberdi escribió las "Bases", texto fundamental que orientó a los constituyentes de 1853.',
  }),
  mc({
    id: 'gna-his-org-7', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'pavon_1861', difficulty: 3,
    stem: 'Tras la batalla de Pavón (1861), quien encabezó la unificación nacional fue:',
    choices: [{ t: 'Bartolomé Mitre.', ok: true }, { t: 'Justo José de Urquiza.' }, { t: 'Juan Manuel de Rosas.' }, { t: 'Nicolás Avellaneda.' }],
    explanation: 'En Pavón, Urquiza se retiró y Mitre quedó en condiciones de unificar el país, siendo luego el primer presidente (1862).',
  }),
  mc({
    id: 'gna-his-org-8', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'guerra_paraguay', difficulty: 3,
    stem: 'La Guerra de la Triple Alianza (1865-1870) enfrentó a Paraguay con:',
    choices: [{ t: 'Argentina, Brasil y Uruguay.', ok: true }, { t: 'Chile, Bolivia y Perú.' }, { t: 'Brasil y Chile solamente.' }, { t: 'España y Gran Bretaña.' }],
    explanation: 'La alianza de Argentina, Brasil y Uruguay combatió contra el Paraguay de Solano López.',
  }),
  mc({
    id: 'gna-his-org-9', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'confederacion', difficulty: 3,
    stem: 'Entre 1853 y 1861, mientras Buenos Aires estuvo separada, la capital de la Confederación Argentina fue:',
    choices: [{ t: 'Paraná.', ok: true }, { t: 'Córdoba.' }, { t: 'Rosario.' }, { t: 'Mendoza.' }],
    explanation: 'La Confederación, presidida por Urquiza, tuvo su capital en Paraná (Entre Ríos).',
  }),

  // ======== Tanda 2: Consolidación del Estado nacional ========
  mc({
    id: 'gna-his-est-5', subject: S, block: 'estado_nacional', topic: 'conquista_del_desierto', difficulty: 2,
    stem: 'La llamada "Conquista del Desierto" (1878-1879), que incorporó territorios patagónicos, fue dirigida por:',
    choices: [{ t: 'Julio A. Roca.', ok: true }, { t: 'Domingo F. Sarmiento.' }, { t: 'Bartolomé Mitre.' }, { t: 'Carlos Pellegrini.' }],
    explanation: 'La campaña militar al mando de Julio A. Roca extendió el dominio estatal sobre la Patagonia.',
  }),
  mc({
    id: 'gna-his-est-6', subject: S, block: 'estado_nacional', topic: 'revolucion_del_parque', difficulty: 3,
    stem: 'La Revolución del Parque (1890) dio origen a un partido que sería clave en el siglo XX:',
    choices: [{ t: 'la Unión Cívica Radical.', ok: true }, { t: 'el Partido Justicialista.' }, { t: 'el Partido Socialista.' }, { t: 'el Partido Autonomista Nacional.' }],
    explanation: 'De la Revolución del Parque y la Unión Cívica surgió luego la Unión Cívica Radical (UCR).',
  }),
  mc({
    id: 'gna-his-est-7', subject: S, block: 'estado_nacional', topic: 'modelo_agroexportador', difficulty: 2,
    stem: 'La economía argentina entre 1880 y 1916 se basó principalmente en:',
    choices: [{ t: 'la exportación de productos agropecuarios.', ok: true }, { t: 'la industria pesada.' }, { t: 'la minería del petróleo.' }, { t: 'la exportación de manufacturas.' }],
    explanation: 'El modelo agroexportador se basó en vender carnes y cereales a Europa e importar manufacturas.',
  }),
  mc({
    id: 'gna-his-est-8', subject: S, block: 'estado_nacional', topic: 'generacion_80', difficulty: 3,
    stem: 'La "Generación del 80" gobernó bajo el lema, de raíz positivista, de:',
    choices: [{ t: '"orden y progreso".', ok: true }, { t: '"paz y administración".' }, { t: '"libertad o muerte".' }, { t: '"pan y trabajo".' }],
    explanation: 'La elite dirigente de 1880 adhirió al positivismo, sintetizado en la idea de "orden y progreso".',
  }),

  // ======== Tanda 2: Radicales y conservadores ========
  mc({
    id: 'gna-his-rad-4', subject: S, block: 'radicales_y_conservadores', topic: 'reforma_universitaria', difficulty: 3,
    stem: 'La Reforma Universitaria de 1918, iniciada en Córdoba durante el gobierno de Yrigoyen, promovió:',
    choices: [{ t: 'la autonomía y el cogobierno universitario.', ok: true }, { t: 'el arancelamiento de la universidad.' }, { t: 'el cierre de las universidades.' }, { t: 'la enseñanza exclusivamente religiosa.' }],
    explanation: 'La Reforma de 1918 introdujo la autonomía, el cogobierno estudiantil y la libertad de cátedra.',
  }),
  mc({
    id: 'gna-his-rad-5', subject: S, block: 'radicales_y_conservadores', topic: 'alvear', difficulty: 2,
    stem: 'Entre las dos presidencias de Yrigoyen gobernó, también por la UCR:',
    choices: [{ t: 'Marcelo T. de Alvear.', ok: true }, { t: 'Agustín P. Justo.' }, { t: 'Roberto M. Ortiz.' }, { t: 'Ramón Castillo.' }],
    explanation: 'Marcelo T. de Alvear (UCR) gobernó entre 1922 y 1928, entre las dos presidencias de Yrigoyen.',
  }),
  mc({
    id: 'gna-his-rad-6', subject: S, block: 'radicales_y_conservadores', topic: 'pacto_roca_runciman', difficulty: 3,
    stem: 'El Pacto Roca-Runciman (1933) fue un acuerdo comercial de Argentina con:',
    choices: [{ t: 'Gran Bretaña, para asegurar la venta de carne.', ok: true }, { t: 'Estados Unidos, sobre el trigo.' }, { t: 'Brasil, sobre el café.' }, { t: 'Alemania, sobre maquinaria.' }],
    explanation: 'El pacto garantizó a Argentina una cuota de exportación de carne al Reino Unido, con fuertes concesiones.',
  }),

  // ======== Tanda 2: Peronismo y posperonismo ========
  mc({
    id: 'gna-his-per-5', subject: S, block: 'peronismo_y_posperonismo', topic: 'diecisiete_octubre', difficulty: 2,
    stem: 'El 17 de octubre de 1945, movilizaciones obreras lograron la liberación de Perón. Esa fecha se conoce como el Día de la:',
    choices: [{ t: 'Lealtad.', ok: true }, { t: 'Independencia.' }, { t: 'Soberanía.' }, { t: 'Revolución.' }],
    explanation: 'El 17 de octubre de 1945 es el Día de la Lealtad peronista, origen simbólico del movimiento.',
  }),
  mc({
    id: 'gna-his-per-6', subject: S, block: 'peronismo_y_posperonismo', topic: 'nacionalizaciones', difficulty: 3,
    stem: 'Durante el primer peronismo, en 1948, el Estado nacionalizó:',
    choices: [{ t: 'los ferrocarriles.', ok: true }, { t: 'la industria automotriz.' }, { t: 'los medios de prensa.' }, { t: 'la actividad agropecuaria.' }],
    explanation: 'En 1948 el gobierno de Perón compró y nacionalizó los ferrocarriles, hasta entonces de capitales británicos.',
  }),
  mc({
    id: 'gna-his-per-7', subject: S, block: 'peronismo_y_posperonismo', topic: 'frondizi', difficulty: 3,
    stem: 'La política de atraer inversiones para producir petróleo y acero, impulsada por Arturo Frondizi, se conoció como:',
    choices: [{ t: 'desarrollismo.', ok: true }, { t: 'liberalismo agrario.' }, { t: 'keynesianismo social.' }, { t: 'neoliberalismo.' }],
    explanation: 'El desarrollismo de Frondizi (1958-1962) buscó el crecimiento mediante inversión en industria pesada y energía.',
  }),
  mc({
    id: 'gna-his-per-8', subject: S, block: 'peronismo_y_posperonismo', topic: 'cordobazo', difficulty: 3,
    stem: 'El "Cordobazo" (1969), gran protesta obrero-estudiantil, ocurrió durante el gobierno de facto de:',
    choices: [{ t: 'Juan Carlos Onganía.', ok: true }, { t: 'Arturo Illia.' }, { t: 'Jorge R. Videla.' }, { t: 'Pedro Aramburu.' }],
    explanation: 'El Cordobazo estalló en 1969 contra la dictadura de Onganía ("Revolución Argentina").',
  }),

  // ======== Tanda 2: Proceso y democracia ========
  mc({
    id: 'gna-his-dem-6', subject: S, block: 'proceso_y_democracia', topic: 'junta_1976', difficulty: 3,
    stem: 'La primera Junta Militar del golpe de 1976 estuvo integrada, por el Ejército, por:',
    choices: [{ t: 'Jorge Rafael Videla.', ok: true }, { t: 'Leopoldo Galtieri.' }, { t: 'Roberto Viola.' }, { t: 'Reynaldo Bignone.' }],
    explanation: 'La primera Junta fue Videla (Ejército), Massera (Marina) y Agosti (Aeronáutica).',
  }),
  mc({
    id: 'gna-his-dem-7', subject: S, block: 'proceso_y_democracia', topic: 'conadep', difficulty: 3,
    stem: 'El informe "Nunca Más", que documentó las violaciones a los derechos humanos de la dictadura, fue elaborado por:',
    choices: [{ t: 'la CONADEP.', ok: true }, { t: 'la Corte Suprema.' }, { t: 'el Congreso de la Nación.' }, { t: 'las Fuerzas Armadas.' }],
    explanation: 'La CONADEP (Comisión Nacional sobre la Desaparición de Personas), creada por Alfonsín en 1983, produjo el "Nunca Más".',
  }),
  mc({
    id: 'gna-his-dem-8', subject: S, block: 'proceso_y_democracia', topic: 'convertibilidad', difficulty: 3,
    stem: 'La Ley de Convertibilidad (1991), durante el gobierno de Menem, estableció que:',
    choices: [{ t: 'un peso equivalía a un dólar.', ok: true }, { t: 'se prohibía el uso del dólar.' }, { t: 'el peso se devaluaba cada mes.' }, { t: 'volvía el austral como moneda.' }],
    explanation: 'La convertibilidad fijó la paridad 1 peso = 1 dólar, con el objetivo de frenar la hiperinflación.',
  }),
  mc({
    id: 'gna-his-dem-9', subject: S, block: 'proceso_y_democracia', topic: 'crisis_2001', difficulty: 2,
    stem: 'La grave crisis social y económica de diciembre de 2001 provocó la renuncia del presidente:',
    choices: [{ t: 'Fernando de la Rúa.', ok: true }, { t: 'Carlos Menem.' }, { t: 'Raúl Alfonsín.' }, { t: 'Néstor Kirchner.' }],
    explanation: 'En diciembre de 2001, en medio de estallidos sociales, Fernando de la Rúa (Alianza) renunció a la presidencia.',
  }),
  mc({
    id: 'gna-his-dem-10', subject: S, block: 'proceso_y_democracia', topic: 'malvinas_causas', difficulty: 2,
    stem: 'El desembarco argentino en las Islas Malvinas, en abril de 1982, fue ordenado por el gobierno de facto de:',
    choices: [{ t: 'Leopoldo Galtieri.', ok: true }, { t: 'Jorge Videla.' }, { t: 'Roberto Viola.' }, { t: 'Reynaldo Bignone.' }],
    explanation: 'El operativo sobre Malvinas fue dispuesto por la junta presidida por Leopoldo Galtieri.',
  }),

  // ================= Tanda 3 =================
  // ---- Antecedentes e Independencia (1806-1820) ----
  mc({ id: 'gna-his-ind-10', subject: S, block: 'independencia_y_anarquia', topic: 'invasiones_inglesas', difficulty: 2,
    stem: 'Las Invasiones Inglesas al Río de la Plata se produjeron en los años:',
    choices: [{ t: '1806 y 1807.', ok: true }, { t: '1810 y 1816.' }, { t: '1820 y 1829.' }, { t: '1852 y 1853.' }],
    explanation: 'En 1806 y 1807 tropas británicas invadieron Buenos Aires; su rechazo fortaleció la conciencia local previa a 1810.' }),
  mc({ id: 'gna-his-ind-11', subject: S, block: 'independencia_y_anarquia', topic: 'reconquista', difficulty: 3,
    stem: 'La Reconquista de Buenos Aires tras la primera invasión inglesa (1806) fue liderada por:',
    choices: [{ t: 'Santiago de Liniers.', ok: true }, { t: 'Cornelio Saavedra.' }, { t: 'Manuel Belgrano.' }, { t: 'Juan José Castelli.' }],
    explanation: 'Santiago de Liniers encabezó la Reconquista en 1806 y luego la Defensa de 1807.' }),
  mc({ id: 'gna-his-ind-12', subject: S, block: 'independencia_y_anarquia', topic: 'causas_revolucion', difficulty: 3,
    stem: 'Un factor externo que impulsó la Revolución de Mayo fue:',
    choices: [{ t: 'la invasión napoleónica a España y la caída de la monarquía.', ok: true }, { t: 'la Guerra de Malvinas.' }, { t: 'la Reforma Universitaria.' }, { t: 'la crisis de 1930.' }],
    explanation: 'La ocupación de España por Napoleón y la prisión de Fernando VII crearon un vacío de poder que precipitó la Revolución.' }),
  mc({ id: 'gna-his-ind-13', subject: S, block: 'independencia_y_anarquia', topic: 'cabildo_abierto', difficulty: 2,
    stem: 'El 22 de mayo de 1810 se realizó un Cabildo Abierto para debatir:',
    choices: [{ t: 'la continuidad o no del virrey Cisneros.', ok: true }, { t: 'la sanción de la Constitución.' }, { t: 'la declaración de la guerra al Brasil.' }, { t: 'la federalización de Buenos Aires.' }],
    explanation: 'El Cabildo Abierto del 22 de mayo discutió la legitimidad del virrey; derivó en la Primera Junta del 25 de mayo.' }),
  mc({ id: 'gna-his-ind-14', subject: S, block: 'independencia_y_anarquia', topic: 'mariano_moreno', difficulty: 3,
    stem: 'El secretario de la Primera Junta que impulsó ideas radicales y fundó la "Gazeta de Buenos Ayres" fue:',
    choices: [{ t: 'Mariano Moreno.', ok: true }, { t: 'Cornelio Saavedra.' }, { t: 'Manuel Belgrano.' }, { t: 'Juan Martín de Pueyrredón.' }],
    explanation: 'Mariano Moreno, secretario de la Junta, promovió la "Gazeta" y un programa revolucionario más radical.' }),
  mc({ id: 'gna-his-ind-15', subject: S, block: 'independencia_y_anarquia', topic: 'exodo_jujeno', difficulty: 3,
    stem: 'El Éxodo Jujeño (1812), en el que la población abandonó y arrasó sus bienes para no dejarlos al enemigo, fue ordenado por:',
    choices: [{ t: 'Manuel Belgrano.', ok: true }, { t: 'Martín Miguel de Güemes.' }, { t: 'José de San Martín.' }, { t: 'Juan José Castelli.' }],
    explanation: 'Belgrano ordenó el Éxodo Jujeño como táctica de tierra arrasada frente al avance realista.' }),
  mc({ id: 'gna-his-ind-16', subject: S, block: 'independencia_y_anarquia', topic: 'batalla_tucuman', difficulty: 3,
    stem: 'Las victorias de Tucumán (1812) y Salta (1813) contra los realistas fueron obtenidas por el ejército de:',
    choices: [{ t: 'Manuel Belgrano.', ok: true }, { t: 'San Martín.' }, { t: 'Güemes.' }, { t: 'Rondeau.' }],
    explanation: 'Belgrano, al mando del Ejército del Norte, venció en Tucumán y Salta.' }),
  mc({ id: 'gna-his-ind-17', subject: S, block: 'independencia_y_anarquia', topic: 'guemes', difficulty: 3,
    stem: 'La defensa de la frontera norte mediante la "guerra gaucha" contra los realistas estuvo a cargo de:',
    choices: [{ t: 'Martín Miguel de Güemes.', ok: true }, { t: 'Cornelio Saavedra.' }, { t: 'Bernardino Rivadavia.' }, { t: 'Juan Lavalle.' }],
    explanation: 'Güemes y sus gauchos salteños frenaron las invasiones realistas desde el norte.' }),
  mc({ id: 'gna-his-ind-18', subject: S, block: 'independencia_y_anarquia', topic: 'cruce_andes_batallas', difficulty: 3,
    stem: 'Tras cruzar los Andes, San Martín aseguró la independencia de Chile con las victorias de:',
    choices: [{ t: 'Chacabuco (1817) y Maipú (1818).', ok: true }, { t: 'Tucumán y Salta.' }, { t: 'Cepeda y Pavón.' }, { t: 'Caseros y Monte Caseros.' }],
    explanation: 'Chacabuco (1817) y Maipú (1818) consolidaron la independencia chilena en la campaña sanmartiniana.' }),
  mc({ id: 'gna-his-ind-19', subject: S, block: 'independencia_y_anarquia', topic: 'lugar_independencia', difficulty: 1,
    stem: 'La Declaración de la Independencia de 1816 se realizó en la ciudad de:',
    choices: [{ t: 'San Miguel de Tucumán.', ok: true }, { t: 'Buenos Aires.' }, { t: 'Córdoba.' }, { t: 'Santa Fe.' }],
    explanation: 'El Congreso que declaró la Independencia el 9 de julio de 1816 sesionó en San Miguel de Tucumán.' }),
  mc({ id: 'gna-his-ind-20', subject: S, block: 'independencia_y_anarquia', topic: 'nombre_pais', difficulty: 3,
    stem: 'En 1816 la Independencia se declaró en nombre de las:',
    choices: [{ t: 'Provincias Unidas de Sudamérica (o del Río de la Plata).', ok: true }, { t: 'República Argentina.' }, { t: 'Confederación Argentina.' }, { t: 'Nación Argentina.' }],
    explanation: 'El Acta de 1816 nombra a las "Provincias Unidas en Sudamérica"; el nombre "República Argentina" se consolidó más tarde.' }),
  mc({ id: 'gna-his-ind-21', subject: S, block: 'independencia_y_anarquia', topic: 'entrevista_guayaquil', difficulty: 3,
    stem: 'En 1822, San Martín se retiró de la campaña libertadora tras entrevistarse en Guayaquil con:',
    choices: [{ t: 'Simón Bolívar.', ok: true }, { t: 'Bernardo O\'Higgins.' }, { t: 'Manuel Belgrano.' }, { t: 'Bernardino Rivadavia.' }],
    explanation: 'La entrevista de Guayaquil (1822) entre San Martín y Bolívar precedió el retiro de San Martín de la lucha.' }),
  mc({ id: 'gna-his-ind-22', subject: S, block: 'independencia_y_anarquia', topic: 'tratado_pilar', difficulty: 3,
    stem: 'Tras la anarquía de 1820, el Tratado del Pilar buscó:',
    choices: [{ t: 'acordar la organización del país entre las provincias.', ok: true }, { t: 'declarar la guerra a España.' }, { t: 'crear la Corte Suprema.' }, { t: 'abolir las provincias.' }],
    explanation: 'El Tratado del Pilar (1820), entre Buenos Aires, Santa Fe y Entre Ríos, intentó pactar la futura organización nacional.' }),

  // ---- Rivadavia, Rosas y Organización (1820-1880) ----
  mc({ id: 'gna-his-org-10', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'rivadavia', difficulty: 3,
    stem: 'Bernardino Rivadavia fue el primer presidente de las Provincias Unidas en el año:',
    choices: [{ t: '1826.', ok: true }, { t: '1810.' }, { t: '1816.' }, { t: '1853.' }],
    explanation: 'Rivadavia asumió en 1826 bajo la Constitución unitaria de ese año, que fue rechazada por las provincias.' }),
  mc({ id: 'gna-his-org-11', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'guerra_brasil', difficulty: 3,
    stem: 'La Guerra con el Brasil (1825-1828) terminó con:',
    choices: [{ t: 'la independencia de la Banda Oriental (Uruguay).', ok: true }, { t: 'la anexión de Brasil a la Argentina.' }, { t: 'la caída de Rosas.' }, { t: 'la federalización de Buenos Aires.' }],
    explanation: 'El conflicto por la Banda Oriental derivó en la creación del Estado independiente del Uruguay (1828).' }),
  mc({ id: 'gna-his-org-12', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'facundo', difficulty: 3,
    stem: 'La obra "Facundo. Civilización y barbarie" fue escrita por:',
    choices: [{ t: 'Domingo F. Sarmiento.', ok: true }, { t: 'Juan Bautista Alberdi.' }, { t: 'Esteban Echeverría.' }, { t: 'Bartolomé Mitre.' }],
    explanation: 'Sarmiento escribió "Facundo" (1845), crítica al caudillismo representado por Facundo Quiroga y a Rosas.' }),
  mc({ id: 'gna-his-org-13', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'vuelta_obligado', difficulty: 3,
    stem: 'El Combate de la Vuelta de Obligado (1845), símbolo de la defensa de la soberanía, enfrentó a la Confederación de Rosas con:',
    choices: [{ t: 'una flota anglo-francesa.', ok: true }, { t: 'el Imperio del Brasil.' }, { t: 'el Paraguay.' }, { t: 'Chile.' }],
    explanation: 'En la Vuelta de Obligado, sobre el Paraná, se resistió el bloqueo de la escuadra anglo-francesa; hoy es el Día de la Soberanía.' }),
  mc({ id: 'gna-his-org-14', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'unitarios_federales', difficulty: 2,
    stem: 'El enfrentamiento político central de la primera mitad del siglo XIX fue entre:',
    choices: [{ t: 'unitarios y federales.', ok: true }, { t: 'radicales y conservadores.' }, { t: 'peronistas y antiperonistas.' }, { t: 'liberales y socialistas.' }],
    explanation: 'Unitarios (poder central en Buenos Aires) y federales (autonomía provincial) marcaron las guerras civiles.' }),
  mc({ id: 'gna-his-org-15', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'acuerdo_san_nicolas', difficulty: 3,
    stem: 'El Acuerdo de San Nicolás (1852) convocó a un congreso para:',
    choices: [{ t: 'dictar una constitución para todo el país.', ok: true }, { t: 'declarar la guerra al Paraguay.' }, { t: 'elegir a Rosas presidente.' }, { t: 'independizar la Patagonia.' }],
    explanation: 'El Acuerdo de San Nicolás, tras Caseros, convocó al Congreso Constituyente que sancionó la Constitución de 1853.' }),
  mc({ id: 'gna-his-org-16', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'presidencia_avellaneda', difficulty: 3,
    stem: 'El presidente que sucedió a Sarmiento (1874-1880) y durante cuya gestión se federalizó Buenos Aires fue:',
    choices: [{ t: 'Nicolás Avellaneda.', ok: true }, { t: 'Julio A. Roca.' }, { t: 'Carlos Pellegrini.' }, { t: 'Bartolomé Mitre.' }],
    explanation: 'Nicolás Avellaneda gobernó de 1874 a 1880; en 1880 se federalizó Buenos Aires bajo su presidencia.' }),
  mc({ id: 'gna-his-org-17', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'sarmiento_obras', difficulty: 2,
    stem: 'Además de fundar escuelas, la presidencia de Sarmiento se destacó por promover:',
    choices: [{ t: 'el telégrafo, el censo y la formación de maestros.', ok: true }, { t: 'la nacionalización del petróleo.' }, { t: 'la reforma agraria.' }, { t: 'el voto femenino.' }],
    explanation: 'Sarmiento impulsó la educación, el primer censo nacional (1869), el telégrafo y la llegada de maestras.' }),
  mc({ id: 'gna-his-org-18', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'caseros_consecuencia', difficulty: 2,
    stem: 'Tras la batalla de Caseros (1852), Juan Manuel de Rosas:',
    choices: [{ t: 'se exilió en Inglaterra.', ok: true }, { t: 'asumió como presidente constitucional.' }, { t: 'fue fusilado.' }, { t: 'firmó la Constitución.' }],
    explanation: 'Derrotado por Urquiza en Caseros, Rosas se exilió en Inglaterra, donde murió en 1877.' }),

  // ---- Estado nacional (1880-1916) ----
  mc({ id: 'gna-his-est-9', subject: S, block: 'estado_nacional', topic: 'roca_lema', difficulty: 2,
    stem: 'El lema de gobierno asociado a la primera presidencia de Julio A. Roca (1880) fue:',
    choices: [{ t: '"paz y administración".', ok: true }, { t: '"orden y progreso".' }, { t: '"pan y trabajo".' }, { t: '"libertad o dependencia".' }],
    explanation: 'La primera presidencia de Roca (1880-1886) se resumió en el lema "paz y administración".' }),
  mc({ id: 'gna-his-est-10', subject: S, block: 'estado_nacional', topic: 'pan', difficulty: 3,
    stem: 'El partido hegemónico que gobernó entre 1880 y 1916 fue:',
    choices: [{ t: 'el Partido Autonomista Nacional (PAN).', ok: true }, { t: 'la Unión Cívica Radical.' }, { t: 'el Partido Justicialista.' }, { t: 'el Partido Socialista.' }],
    explanation: 'El PAN, expresión de la elite conservadora, dominó la política entre 1880 y el fin del régimen oligárquico.' }),
  mc({ id: 'gna-his-est-11', subject: S, block: 'estado_nacional', topic: 'ley_residencia', difficulty: 3,
    stem: 'La Ley de Residencia (1902) permitió al gobierno:',
    choices: [{ t: 'expulsar a extranjeros considerados peligrosos.', ok: true }, { t: 'otorgar tierras a los inmigrantes.' }, { t: 'establecer el voto obligatorio.' }, { t: 'nacionalizar los ferrocarriles.' }],
    explanation: 'La Ley 4144 de Residencia habilitó la expulsión de extranjeros, usada contra dirigentes obreros y anarquistas.' }),
  mc({ id: 'gna-his-est-12', subject: S, block: 'estado_nacional', topic: 'movimiento_obrero', difficulty: 3,
    stem: 'A comienzos del siglo XX, entre los inmigrantes se difundieron ideologías obreras como:',
    choices: [{ t: 'el anarquismo y el socialismo.', ok: true }, { t: 'el peronismo.' }, { t: 'el radicalismo agrario.' }, { t: 'el nacionalismo militar.' }],
    explanation: 'El movimiento obrero de principios del siglo XX estuvo influido por el anarquismo y el socialismo traídos por inmigrantes.' }),
  mc({ id: 'gna-his-est-13', subject: S, block: 'estado_nacional', topic: 'primer_censo', difficulty: 3,
    stem: 'El primer censo nacional de la Argentina se realizó en 1869 durante la presidencia de:',
    choices: [{ t: 'Domingo F. Sarmiento.', ok: true }, { t: 'Bartolomé Mitre.' }, { t: 'Julio A. Roca.' }, { t: 'Nicolás Avellaneda.' }],
    explanation: 'El primer censo nacional (1869) se llevó a cabo bajo la presidencia de Sarmiento.' }),
  mc({ id: 'gna-his-est-14', subject: S, block: 'estado_nacional', topic: 'roque_saenz_pena', difficulty: 2,
    stem: 'El presidente que impulsó la ley del voto secreto y obligatorio de 1912 fue:',
    choices: [{ t: 'Roque Sáenz Peña.', ok: true }, { t: 'Julio A. Roca.' }, { t: 'Hipólito Yrigoyen.' }, { t: 'Carlos Pellegrini.' }],
    explanation: 'La ley de 1912 lleva el nombre del presidente Roque Sáenz Peña, que la promovió.' }),

  // ---- Radicales y conservadores (1916-1943) ----
  mc({ id: 'gna-his-rad-7', subject: S, block: 'radicales_y_conservadores', topic: 'semana_tragica', difficulty: 3,
    stem: 'La "Semana Trágica" de enero de 1919 fue:',
    choices: [{ t: 'una dura represión a huelgas obreras en Buenos Aires.', ok: true }, { t: 'un golpe de Estado.' }, { t: 'una guerra con Chile.' }, { t: 'la reforma de la Constitución.' }],
    explanation: 'La Semana Trágica fue una violenta represión de conflictos obreros durante el gobierno de Yrigoyen.' }),
  mc({ id: 'gna-his-rad-8', subject: S, block: 'radicales_y_conservadores', topic: 'ypf', difficulty: 3,
    stem: 'La empresa estatal petrolera YPF fue organizada en los años 20 por el general:',
    choices: [{ t: 'Enrique Mosconi.', ok: true }, { t: 'Agustín P. Justo.' }, { t: 'José F. Uriburu.' }, { t: 'Juan D. Perón.' }],
    explanation: 'Enrique Mosconi impulsó y organizó YPF (Yacimientos Petrolíferos Fiscales) como empresa estatal.' }),
  mc({ id: 'gna-his-rad-9', subject: S, block: 'radicales_y_conservadores', topic: 'uriburu', difficulty: 3,
    stem: 'El golpe de 1930 fue encabezado por el general:',
    choices: [{ t: 'José Félix Uriburu.', ok: true }, { t: 'Agustín P. Justo.' }, { t: 'Pedro Aramburu.' }, { t: 'Juan Carlos Onganía.' }],
    explanation: 'José Félix Uriburu lideró el golpe del 6 de septiembre de 1930 contra Yrigoyen.' }),
  mc({ id: 'gna-his-rad-10', subject: S, block: 'radicales_y_conservadores', topic: 'fraude_patriotico', difficulty: 3,
    stem: 'El "fraude patriótico" de la década de 1930 consistió en:',
    choices: [{ t: 'manipular las elecciones para mantener el poder conservador.', ok: true }, { t: 'ampliar el sufragio a las mujeres.' }, { t: 'nacionalizar los servicios públicos.' }, { t: 'crear el voto electrónico.' }],
    explanation: 'Los gobiernos conservadores justificaban el fraude electoral como forma de impedir el regreso del radicalismo.' }),
  mc({ id: 'gna-his-rad-11', subject: S, block: 'radicales_y_conservadores', topic: 'golpe_1943', difficulty: 3,
    stem: 'El golpe de 1943, que abrió el camino al ascenso de Perón, fue protagonizado por:',
    choices: [{ t: 'un sector del Ejército (el GOU).', ok: true }, { t: 'la Unión Cívica Radical.' }, { t: 'el Partido Socialista.' }, { t: 'la Iglesia Católica.' }],
    explanation: 'El golpe de junio de 1943 fue militar; en ese contexto Perón ganó influencia desde la Secretaría de Trabajo.' }),

  // ---- Peronismo y posperonismo (1943-1976) ----
  mc({ id: 'gna-his-per-9', subject: S, block: 'peronismo_y_posperonismo', topic: 'secretaria_trabajo', difficulty: 3,
    stem: 'Perón ganó apoyo popular, antes de ser presidente, desde su cargo en:',
    choices: [{ t: 'la Secretaría de Trabajo y Previsión.', ok: true }, { t: 'el Ministerio de Economía.' }, { t: 'la Corte Suprema.' }, { t: 'la Cancillería.' }],
    explanation: 'Desde la Secretaría de Trabajo (1943-1945) Perón impulsó leyes laborales que le dieron respaldo obrero.' }),
  mc({ id: 'gna-his-per-10', subject: S, block: 'peronismo_y_posperonismo', topic: 'primera_presidencia', difficulty: 2,
    stem: 'Juan Domingo Perón fue elegido presidente por primera vez en:',
    choices: [{ t: '1946.', ok: true }, { t: '1943.' }, { t: '1955.' }, { t: '1973.' }],
    explanation: 'Perón ganó las elecciones de febrero de 1946 y asumió su primera presidencia.' }),
  mc({ id: 'gna-his-per-11', subject: S, block: 'peronismo_y_posperonismo', topic: 'derechos_laborales', difficulty: 2,
    stem: 'El primer peronismo se caracterizó, en lo social, por:',
    choices: [{ t: 'ampliar los derechos de los trabajadores (aguinaldo, vacaciones, jubilaciones).', ok: true }, { t: 'reducir el gasto social.' }, { t: 'prohibir los sindicatos.' }, { t: 'eliminar el salario mínimo.' }],
    explanation: 'El peronismo consolidó derechos laborales como el aguinaldo, las vacaciones pagas y el sistema previsional.' }),
  mc({ id: 'gna-his-per-12', subject: S, block: 'peronismo_y_posperonismo', topic: 'eva_peron', difficulty: 2,
    stem: 'Eva Perón tuvo un papel destacado en:',
    choices: [{ t: 'la ayuda social y la conquista de los derechos políticos de la mujer.', ok: true }, { t: 'la conducción del Ejército.' }, { t: 'la presidencia de la Corte Suprema.' }, { t: 'la dirección de YPF.' }],
    explanation: 'Eva Perón impulsó la Fundación de ayuda social y el voto femenino (1947), y fundó el Partido Peronista Femenino.' }),
  mc({ id: 'gna-his-per-13', subject: S, block: 'peronismo_y_posperonismo', topic: 'lonardi_aramburu', difficulty: 3,
    stem: 'Tras derrocar a Perón en 1955, la "Revolución Libertadora" fue presidida sucesivamente por:',
    choices: [{ t: 'Lonardi y luego Aramburu.', ok: true }, { t: 'Frondizi e Illia.' }, { t: 'Onganía y Lanusse.' }, { t: 'Videla y Viola.' }],
    explanation: 'Eduardo Lonardi asumió en 1955 y fue reemplazado por Pedro E. Aramburu.' }),
  mc({ id: 'gna-his-per-14', subject: S, block: 'peronismo_y_posperonismo', topic: 'proscripcion', difficulty: 3,
    stem: 'Entre 1955 y 1973, un rasgo central de la política argentina fue:',
    choices: [{ t: 'la proscripción del peronismo.', ok: true }, { t: 'la vigencia plena de la Constitución de 1949.' }, { t: 'la reelección indefinida.' }, { t: 'la ausencia de gobiernos militares.' }],
    explanation: 'El peronismo estuvo proscripto (prohibido de presentarse en elecciones) durante gran parte de ese período.' }),
  mc({ id: 'gna-his-per-15', subject: S, block: 'peronismo_y_posperonismo', topic: 'illia', difficulty: 3,
    stem: 'El presidente radical derrocado por el golpe de 1966 fue:',
    choices: [{ t: 'Arturo Illia.', ok: true }, { t: 'Arturo Frondizi.' }, { t: 'José María Guido.' }, { t: 'Raúl Alfonsín.' }],
    explanation: 'Arturo Illia (UCR del Pueblo) fue derrocado en 1966 por la autodenominada "Revolución Argentina".' }),
  mc({ id: 'gna-his-per-16', subject: S, block: 'peronismo_y_posperonismo', topic: 'campora_1973', difficulty: 3,
    stem: 'En 1973, con el lema "Cámpora al gobierno, Perón al poder", asumió la presidencia:',
    choices: [{ t: 'Héctor J. Cámpora.', ok: true }, { t: 'Juan D. Perón.' }, { t: 'Isabel Martínez de Perón.' }, { t: 'Arturo Frondizi.' }],
    explanation: 'Cámpora asumió en mayo de 1973 y renunció para permitir nuevas elecciones que consagraron a Perón.' }),
  mc({ id: 'gna-his-per-17', subject: S, block: 'peronismo_y_posperonismo', topic: 'tercera_presidencia', difficulty: 2,
    stem: 'Al morir Juan D. Perón en 1974, lo sucedió en la presidencia:',
    choices: [{ t: 'María Estela (Isabel) Martínez de Perón.', ok: true }, { t: 'Ítalo Luder.' }, { t: 'Raúl Lastiri.' }, { t: 'Héctor Cámpora.' }],
    explanation: 'Su esposa y vicepresidenta, Isabel Perón, asumió en 1974 y fue derrocada en marzo de 1976.' }),
  mc({ id: 'gna-his-per-18', subject: S, block: 'peronismo_y_posperonismo', topic: 'frondizi_petroleo', difficulty: 3,
    stem: 'El desarrollismo de Frondizi promovió la autosuficiencia en materia de:',
    choices: [{ t: 'petróleo y siderurgia.', ok: true }, { t: 'producción de trigo.' }, { t: 'exportación de lana.' }, { t: 'turismo.' }],
    explanation: 'Frondizi impulsó contratos petroleros y la industria pesada (acero) para el desarrollo nacional.' }),

  // ---- Proceso y democracia (1976-actualidad) ----
  mc({ id: 'gna-his-dem-11', subject: S, block: 'proceso_y_democracia', topic: 'terrorismo_estado', difficulty: 2,
    stem: 'El "Proceso de Reorganización Nacional" (1976-1983) se caracterizó por:',
    choices: [{ t: 'el terrorismo de Estado y la desaparición forzada de personas.', ok: true }, { t: 'la ampliación de las libertades públicas.' }, { t: 'la vigencia plena del Congreso.' }, { t: 'la realización de elecciones libres.' }],
    explanation: 'La dictadura implementó un plan sistemático de represión ilegal, con miles de desaparecidos.' }),
  mc({ id: 'gna-his-dem-12', subject: S, block: 'proceso_y_democracia', topic: 'martinez_de_hoz', difficulty: 3,
    stem: 'El ministro de Economía del Proceso, asociado a la apertura y el endeudamiento, fue:',
    choices: [{ t: 'José A. Martínez de Hoz.', ok: true }, { t: 'Domingo Cavallo.' }, { t: 'Bernardo Grinspun.' }, { t: 'Roberto Lavagna.' }],
    explanation: 'Martínez de Hoz condujo la economía de la dictadura, con apertura financiera y fuerte aumento de la deuda externa.' }),
  mc({ id: 'gna-his-dem-13', subject: S, block: 'proceso_y_democracia', topic: 'madres_plaza', difficulty: 2,
    stem: 'El organismo de derechos humanos que reclamó por los desaparecidos rondando la plaza frente a la Casa de Gobierno fue:',
    choices: [{ t: 'Madres de Plaza de Mayo.', ok: true }, { t: 'la CGT.' }, { t: 'la Sociedad Rural.' }, { t: 'el PAN.' }],
    explanation: 'Las Madres de Plaza de Mayo comenzaron en 1977 a reclamar por sus hijos desaparecidos.' }),
  mc({ id: 'gna-his-dem-14', subject: S, block: 'proceso_y_democracia', topic: 'alfonsin_ddhh', difficulty: 3,
    stem: 'Entre las primeras medidas de Alfonsín en 1983 estuvo:',
    choices: [{ t: 'crear la CONADEP para investigar los crímenes de la dictadura.', ok: true }, { t: 'establecer la convertibilidad.' }, { t: 'privatizar las empresas públicas.' }, { t: 'declarar la guerra a Chile.' }],
    explanation: 'Alfonsín creó la CONADEP y promovió el Juicio a las Juntas (1985).' }),
  mc({ id: 'gna-his-dem-15', subject: S, block: 'proceso_y_democracia', topic: 'hiperinflacion', difficulty: 3,
    stem: 'El gobierno de Alfonsín terminó anticipadamente en 1989 en un contexto de:',
    choices: [{ t: 'hiperinflación y crisis económica.', ok: true }, { t: 'golpe militar.' }, { t: 'guerra externa.' }, { t: 'reforma constitucional.' }],
    explanation: 'La hiperinflación de 1989 precipitó la entrega anticipada del poder a Carlos Menem.' }),
  mc({ id: 'gna-his-dem-16', subject: S, block: 'proceso_y_democracia', topic: 'privatizaciones', difficulty: 3,
    stem: 'Durante los años 90, la política económica de Menem incluyó:',
    choices: [{ t: 'la privatización de empresas estatales.', ok: true }, { t: 'la estatización de la banca.' }, { t: 'la reforma agraria.' }, { t: 'el cierre de las exportaciones.' }],
    explanation: 'El menemismo privatizó empresas públicas (teléfonos, aerolíneas, YPF, servicios) en el marco del Consenso de Washington.' }),
  mc({ id: 'gna-his-dem-17', subject: S, block: 'proceso_y_democracia', topic: 'pacto_olivos', difficulty: 3,
    stem: 'El acuerdo político que habilitó la reforma constitucional de 1994 se conoció como:',
    choices: [{ t: 'el Pacto de Olivos (Menem-Alfonsín).', ok: true }, { t: 'el Pacto de San José.' }, { t: 'el Acuerdo de San Nicolás.' }, { t: 'el Pacto Federal.' }],
    explanation: 'El Pacto de Olivos entre Menem y Alfonsín (1993) fijó las bases de la reforma de 1994.' }),
  mc({ id: 'gna-his-dem-18', subject: S, block: 'proceso_y_democracia', topic: 'crisis_2001_sucesion', difficulty: 3,
    stem: 'Tras la renuncia de De la Rúa (2001), asumió finalmente la presidencia, designado por la Asamblea Legislativa:',
    choices: [{ t: 'Eduardo Duhalde.', ok: true }, { t: 'Néstor Kirchner.' }, { t: 'Mauricio Macri.' }, { t: 'Carlos Menem.' }],
    explanation: 'Tras una sucesión de presidentes provisionales, Eduardo Duhalde fue designado en enero de 2002 hasta llamar a elecciones.' }),
  mc({ id: 'gna-his-dem-19', subject: S, block: 'proceso_y_democracia', topic: 'obediencia_debida', difficulty: 3,
    stem: 'Las leyes de Punto Final y Obediencia Debida, sancionadas en los años 80, buscaban:',
    choices: [{ t: 'limitar los juicios a los militares por la represión.', ok: true }, { t: 'ampliar los juicios a todos los responsables.' }, { t: 'restaurar la Constitución de 1949.' }, { t: 'privatizar YPF.' }],
    explanation: 'Punto Final (1986) y Obediencia Debida (1987) frenaron los juicios; fueron anuladas años después.' }),
  mc({ id: 'gna-his-dem-20', subject: S, block: 'proceso_y_democracia', topic: 'malvinas_resultado', difficulty: 2,
    stem: 'La Guerra de Malvinas (1982) terminó con:',
    choices: [{ t: 'la rendición argentina y el debilitamiento de la dictadura.', ok: true }, { t: 'la recuperación definitiva de las islas.' }, { t: 'un tratado de paz con soberanía compartida.' }, { t: 'la anexión de las islas por Chile.' }],
    explanation: 'La derrota militar en Malvinas aceleró la caída de la dictadura y la transición a la democracia en 1983.' }),

  // ================= Tanda 4 =================
  // ---- Independencia y anarquía ----
  mc({ id: 'gna-his-ind-23', subject: S, block: 'independencia_y_anarquia', topic: 'defensa_1807', difficulty: 3,
    stem: 'La Defensa de Buenos Aires ante la segunda invasión inglesa (1807) demostró la capacidad militar de las milicias locales lideradas por:',
    choices: [{ t: 'Santiago de Liniers.', ok: true }, { t: 'Bernardino Rivadavia.' }, { t: 'Mariano Moreno.' }, { t: 'Manuel Belgrano.' }],
    explanation: 'Liniers organizó la Defensa de 1807, que rechazó la segunda invasión británica.' }),
  mc({ id: 'gna-his-ind-24', subject: S, block: 'independencia_y_anarquia', topic: 'primera_junta_integrantes', difficulty: 3,
    stem: 'Además de Saavedra (presidente), Mariano Moreno y Juan José Paso fueron, en la Primera Junta:',
    choices: [{ t: 'secretarios.', ok: true }, { t: 'vocales militares.' }, { t: 'virreyes.' }, { t: 'gobernadores de provincia.' }],
    explanation: 'Moreno y Paso ocuparon las secretarías de la Primera Junta de 1810.' }),
  mc({ id: 'gna-his-ind-25', subject: S, block: 'independencia_y_anarquia', topic: 'gazeta', difficulty: 3,
    stem: 'La "Gazeta de Buenos Ayres", primer periódico oficial de la Revolución, fue impulsada por:',
    choices: [{ t: 'Mariano Moreno.', ok: true }, { t: 'Cornelio Saavedra.' }, { t: 'Juan Manuel de Rosas.' }, { t: 'Bernardino Rivadavia.' }],
    explanation: 'Moreno fundó la "Gazeta" en 1810 para difundir las ideas y actos de la Junta.' }),
  mc({ id: 'gna-his-ind-26', subject: S, block: 'independencia_y_anarquia', topic: 'himno', difficulty: 2,
    stem: 'El Himno Nacional Argentino fue aprobado en 1813 por:',
    choices: [{ t: 'la Asamblea del Año XIII.', ok: true }, { t: 'el Congreso de Tucumán.' }, { t: 'la Primera Junta.' }, { t: 'el Directorio.' }],
    explanation: 'La Asamblea del Año XIII aprobó la marcha patriótica que se convirtió en el Himno Nacional.' }),
  mc({ id: 'gna-his-ind-27', subject: S, block: 'independencia_y_anarquia', topic: 'libertad_vientres', difficulty: 3,
    stem: 'La "libertad de vientres", sancionada por la Asamblea del Año XIII, establecía que:',
    choices: [{ t: 'los hijos de esclavos nacían libres.', ok: true }, { t: 'se abolía totalmente la esclavitud.' }, { t: 'se prohibía la inmigración.' }, { t: 'se creaba la moneda nacional.' }],
    explanation: 'La libertad de vientres declaró libres a los hijos de esclavas nacidos desde 1813, sin abolir de inmediato la esclavitud.' }),
  mc({ id: 'gna-his-ind-28', subject: S, block: 'independencia_y_anarquia', topic: 'artigas', difficulty: 3,
    stem: 'El caudillo federal, líder de la Banda Oriental y de los pueblos del Litoral, fue:',
    choices: [{ t: 'José Gervasio Artigas.', ok: true }, { t: 'Juan Manuel de Rosas.' }, { t: 'Facundo Quiroga.' }, { t: 'Estanislao López.' }],
    explanation: 'Artigas, "Protector de los Pueblos Libres", defendió el federalismo desde la Banda Oriental.' }),
  mc({ id: 'gna-his-ind-29', subject: S, block: 'independencia_y_anarquia', topic: 'granaderos', difficulty: 3,
    stem: 'El Regimiento de Granaderos a Caballo fue creado por:',
    choices: [{ t: 'José de San Martín.', ok: true }, { t: 'Manuel Belgrano.' }, { t: 'Martín de Güemes.' }, { t: 'Cornelio Saavedra.' }],
    explanation: 'San Martín organizó los Granaderos a Caballo, cuerpo de élite que debutó en San Lorenzo (1813).' }),
  mc({ id: 'gna-his-ind-30', subject: S, block: 'independencia_y_anarquia', topic: 'directorio', difficulty: 3,
    stem: 'El cargo de máxima autoridad ejecutiva entre 1814 y 1820 se denominó:',
    choices: [{ t: 'Director Supremo.', ok: true }, { t: 'Presidente.' }, { t: 'Gobernador general.' }, { t: 'Cónsul.' }],
    explanation: 'El Directorio, con el Director Supremo a la cabeza, gobernó las Provincias Unidas hasta la crisis de 1820.' }),
  mc({ id: 'gna-his-ind-31', subject: S, block: 'independencia_y_anarquia', topic: 'san_martin_libertador', difficulty: 1,
    stem: 'José de San Martín es reconocido como Libertador de:',
    choices: [{ t: 'Argentina, Chile y Perú.', ok: true }, { t: 'Argentina, Brasil y Uruguay.' }, { t: 'México y Colombia.' }, { t: 'España y Portugal.' }],
    explanation: 'San Martín encabezó la independencia del sur de Sudamérica: Argentina, Chile y Perú.' }),
  mc({ id: 'gna-his-ind-32', subject: S, block: 'independencia_y_anarquia', topic: 'belgrano_bandera_lugar', difficulty: 2,
    stem: 'Belgrano enarboló por primera vez la bandera a orillas del río Paraná, en la actual ciudad de:',
    choices: [{ t: 'Rosario.', ok: true }, { t: 'Santa Fe.' }, { t: 'Paraná.' }, { t: 'Corrientes.' }],
    explanation: 'El 27 de febrero de 1812 Belgrano izó la bandera en las baterías del río Paraná, en Rosario.' }),

  // ---- Rosas y Organización nacional ----
  mc({ id: 'gna-his-org-19', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'suma_poder', difficulty: 3,
    stem: 'En su segundo gobierno, Rosas ejerció con amplias facultades conocidas como:',
    choices: [{ t: 'la suma del poder público.', ok: true }, { t: 'la coparticipación federal.' }, { t: 'el estado de sitio permanente.' }, { t: 'la autonomía municipal.' }],
    explanation: 'La Legislatura otorgó a Rosas la "suma del poder público", concentrando facultades extraordinarias.' }),
  mc({ id: 'gna-his-org-20', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'divisa_punzo', difficulty: 3,
    stem: 'El color asociado al federalismo rosista, de uso obligatorio, era:',
    choices: [{ t: 'el rojo (divisa punzó).', ok: true }, { t: 'el celeste.' }, { t: 'el verde.' }, { t: 'el amarillo.' }],
    explanation: 'La divisa punzó (roja) era símbolo obligatorio del federalismo bajo Rosas.' }),
  mc({ id: 'gna-his-org-21', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'generacion_37', difficulty: 3,
    stem: 'El grupo de intelectuales opositores a Rosas (Echeverría, Alberdi, Sarmiento) es conocido como:',
    choices: [{ t: 'la Generación del 37.', ok: true }, { t: 'la Generación del 80.' }, { t: 'la Reforma del 18.' }, { t: 'la Década Infame.' }],
    explanation: 'La Generación del 37, romántica y liberal, sentó bases ideológicas de la organización nacional.' }),
  mc({ id: 'gna-his-org-22', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'urquiza_entre_rios', difficulty: 3,
    stem: 'Justo José de Urquiza, vencedor de Caseros, era gobernador de la provincia de:',
    choices: [{ t: 'Entre Ríos.', ok: true }, { t: 'Buenos Aires.' }, { t: 'Corrientes.' }, { t: 'Santa Fe.' }],
    explanation: 'Urquiza gobernaba Entre Ríos cuando encabezó el Ejército Grande contra Rosas.' }),
  mc({ id: 'gna-his-org-23', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'secesion_bsas', difficulty: 3,
    stem: 'Tras la Constitución de 1853, Buenos Aires:',
    choices: [{ t: 'se separó de la Confederación durante varios años.', ok: true }, { t: 'fue federalizada de inmediato.' }, { t: 'declaró la guerra al Paraguay.' }, { t: 'eligió a Urquiza gobernador.' }],
    explanation: 'Buenos Aires se mantuvo separada de la Confederación entre 1853 y su incorporación tras Pavón (1861).' }),
  mc({ id: 'gna-his-org-24', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'constitucion_modelo', difficulty: 3,
    stem: 'La Constitución de 1853 se inspiró en el modelo de:',
    choices: [{ t: 'los Estados Unidos (federal y presidencialista).', ok: true }, { t: 'la monarquía británica.' }, { t: 'la Unión Soviética.' }, { t: 'el Imperio del Brasil.' }],
    explanation: 'Tomó como modelo la Constitución federal y presidencialista de los Estados Unidos, adaptada por Alberdi.' }),
  mc({ id: 'gna-his-org-25', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'guerra_paraguay_fin', difficulty: 3,
    stem: 'La Guerra del Paraguay (Triple Alianza) finalizó en 1870 con:',
    choices: [{ t: 'la derrota total del Paraguay y la muerte de Solano López.', ok: true }, { t: 'la victoria paraguaya.' }, { t: 'un empate y statu quo.' }, { t: 'la anexión de Brasil a la Argentina.' }],
    explanation: 'La guerra terminó en 1870 con la devastación del Paraguay y la muerte de Francisco Solano López.' }),

  // ---- Estado nacional ----
  mc({ id: 'gna-his-est-15', subject: S, block: 'estado_nacional', topic: 'grito_alcorta', difficulty: 3,
    stem: 'El "Grito de Alcorta" (1912) fue una protesta de:',
    choices: [{ t: 'pequeños chacareros y arrendatarios rurales.', ok: true }, { t: 'obreros ferroviarios.' }, { t: 'estudiantes universitarios.' }, { t: 'militares.' }],
    explanation: 'El Grito de Alcorta fue una huelga agraria de arrendatarios santafesinos que dio origen a la Federación Agraria.' }),
  mc({ id: 'gna-his-est-16', subject: S, block: 'estado_nacional', topic: 'inmigracion_efectos', difficulty: 2,
    stem: 'Un efecto de la gran inmigración europea fue:',
    choices: [{ t: 'el rápido crecimiento y la diversificación de la población.', ok: true }, { t: 'la despoblación de las ciudades.' }, { t: 'el retroceso de la agricultura.' }, { t: 'la desaparición del castellano.' }],
    explanation: 'La inmigración multiplicó la población, urbanizó el país y transformó su composición social y cultural.' }),
  mc({ id: 'gna-his-est-17', subject: S, block: 'estado_nacional', topic: 'ferrocarriles', difficulty: 2,
    stem: 'La expansión del ferrocarril entre 1880 y 1916 sirvió principalmente para:',
    choices: [{ t: 'transportar la producción agropecuaria hacia los puertos.', ok: true }, { t: 'trasladar tropas a Malvinas.' }, { t: 'conectar con Europa.' }, { t: 'distribuir petróleo.' }],
    explanation: 'La red ferroviaria, en gran parte de capital británico, articuló el modelo agroexportador hacia los puertos.' }),
  mc({ id: 'gna-his-est-18', subject: S, block: 'estado_nacional', topic: 'pellegrini', difficulty: 3,
    stem: 'Tras la crisis de 1890, completó el mandato presidencial y fundó el Banco de la Nación:',
    choices: [{ t: 'Carlos Pellegrini.', ok: true }, { t: 'Miguel Juárez Celman.' }, { t: 'Julio A. Roca.' }, { t: 'Luis Sáenz Peña.' }],
    explanation: 'Carlos Pellegrini asumió tras la renuncia de Juárez Celman (1890) y creó el Banco de la Nación Argentina.' }),
  mc({ id: 'gna-his-est-19', subject: S, block: 'estado_nacional', topic: 'conquista_consecuencia', difficulty: 3,
    stem: 'Una consecuencia de la Conquista del Desierto fue:',
    choices: [{ t: 'la incorporación de vastas tierras y el sometimiento de los pueblos indígenas.', ok: true }, { t: 'la independencia de la Patagonia.' }, { t: 'la creación de la UCR.' }, { t: 'la sanción de la Ley Sáenz Peña.' }],
    explanation: 'La campaña extendió el territorio estatal a costa de las comunidades originarias del sur.' }),
  mc({ id: 'gna-his-est-20', subject: S, block: 'estado_nacional', topic: 'roca_presidencias', difficulty: 3,
    stem: 'Julio A. Roca ejerció la presidencia de la Nación en:',
    choices: [{ t: 'dos períodos (1880-1886 y 1898-1904).', ok: true }, { t: 'un solo período.' }, { t: 'tres períodos consecutivos.' }, { t: 'ningún período (solo fue militar).' }],
    explanation: 'Roca fue presidente en dos mandatos no consecutivos, figura central del régimen conservador.' }),

  // ---- Radicales y conservadores ----
  mc({ id: 'gna-his-rad-12', subject: S, block: 'radicales_y_conservadores', topic: 'yrigoyen_estilo', difficulty: 3,
    stem: 'El primer gobierno de Yrigoyen (1916-1922) se caracterizó por:',
    choices: [{ t: 'ampliar la participación política y cierta intervención social.', ok: true }, { t: 'privatizar los ferrocarriles.' }, { t: 'derogar el voto secreto.' }, { t: 'declarar la guerra a Chile.' }],
    explanation: 'El yrigoyenismo amplió la participación de las clases medias y adoptó políticas de mediación social.' }),
  mc({ id: 'gna-his-rad-13', subject: S, block: 'radicales_y_conservadores', topic: 'primera_guerra', difficulty: 3,
    stem: 'Durante la Primera Guerra Mundial (1914-1918), Argentina mantuvo una política de:',
    choices: [{ t: 'neutralidad.', ok: true }, { t: 'participación junto a Alemania.' }, { t: 'invasión de Europa.' }, { t: 'alianza militar con EE.UU.' }],
    explanation: 'El gobierno radical de Yrigoyen sostuvo la neutralidad argentina durante la Gran Guerra.' }),
  mc({ id: 'gna-his-rad-14', subject: S, block: 'radicales_y_conservadores', topic: 'justo', difficulty: 3,
    stem: 'El presidente que gobernó durante buena parte de la "Década Infame" (1932-1938) fue:',
    choices: [{ t: 'Agustín P. Justo.', ok: true }, { t: 'Hipólito Yrigoyen.' }, { t: 'Marcelo T. de Alvear.' }, { t: 'Ramón Castillo.' }],
    explanation: 'Agustín P. Justo gobernó de 1932 a 1938 en el marco del régimen conservador y fraudulento.' }),
  mc({ id: 'gna-his-rad-15', subject: S, block: 'radicales_y_conservadores', topic: 'crisis_1929', difficulty: 3,
    stem: 'La crisis económica mundial de 1929 impactó en Argentina provocando:',
    choices: [{ t: 'la caída de las exportaciones y una mayor intervención del Estado.', ok: true }, { t: 'un boom exportador sin precedentes.' }, { t: 'la nacionalización del petróleo.' }, { t: 'la reforma constitucional.' }],
    explanation: 'La Gran Depresión redujo el comercio exterior e impulsó políticas de intervención estatal y sustitución de importaciones.' }),

  // ---- Peronismo y posperonismo ----
  mc({ id: 'gna-his-per-19', subject: S, block: 'peronismo_y_posperonismo', topic: 'iapi', difficulty: 3,
    stem: 'El organismo estatal que centralizó el comercio exterior durante el primer peronismo fue:',
    choices: [{ t: 'el IAPI.', ok: true }, { t: 'YPF.' }, { t: 'el Banco Central privado.' }, { t: 'la CONADEP.' }],
    explanation: 'El IAPI (Instituto Argentino de Promoción del Intercambio) manejó el comercio exterior y transfirió recursos a la industria.' }),
  mc({ id: 'gna-his-per-20', subject: S, block: 'peronismo_y_posperonismo', topic: 'planes_quinquenales', difficulty: 3,
    stem: 'La planificación económica del primer peronismo se expresó en los llamados:',
    choices: [{ t: 'planes quinquenales.', ok: true }, { t: 'planes de convertibilidad.' }, { t: 'pactos de Olivos.' }, { t: 'acuerdos de San Nicolás.' }],
    explanation: 'El peronismo implementó Planes Quinquenales para orientar la economía y la industrialización.' }),
  mc({ id: 'gna-his-per-21', subject: S, block: 'peronismo_y_posperonismo', topic: 'cgt', difficulty: 2,
    stem: 'La central sindical que se consolidó como base del movimiento obrero peronista es:',
    choices: [{ t: 'la CGT.', ok: true }, { t: 'la Sociedad Rural.' }, { t: 'la UIA.' }, { t: 'la Bolsa de Comercio.' }],
    explanation: 'La Confederación General del Trabajo (CGT) fue el pilar sindical del peronismo.' }),
  mc({ id: 'gna-his-per-22', subject: S, block: 'peronismo_y_posperonismo', topic: 'voto_femenino_ley', difficulty: 2,
    stem: 'La ley que consagró el voto femenino en 1947 lleva el número:',
    choices: [{ t: '13.010.', ok: true }, { t: '1.420.' }, { t: '8.871.' }, { t: '4.144.' }],
    explanation: 'La Ley 13.010 (1947) reconoció los derechos políticos de la mujer; la 8871 es la Sáenz Peña y la 1420, de educación.' }),
  mc({ id: 'gna-his-per-23', subject: S, block: 'peronismo_y_posperonismo', topic: 'bombardeo_1955', difficulty: 3,
    stem: 'En junio de 1955, en el marco del conflicto con Perón, ocurrió:',
    choices: [{ t: 'el bombardeo a la Plaza de Mayo.', ok: true }, { t: 'la Guerra de Malvinas.' }, { t: 'el Cordobazo.' }, { t: 'la Semana Trágica.' }],
    explanation: 'El bombardeo de la aviación naval a Plaza de Mayo (junio de 1955) precedió al golpe de septiembre.' }),
  mc({ id: 'gna-his-per-24', subject: S, block: 'peronismo_y_posperonismo', topic: 'fusilamientos_1956', difficulty: 3,
    stem: 'Tras un levantamiento peronista en 1956, el gobierno de la "Libertadora" respondió con:',
    choices: [{ t: 'fusilamientos de militares y civiles.', ok: true }, { t: 'la restitución de Perón.' }, { t: 'la reforma agraria.' }, { t: 'elecciones inmediatas.' }],
    explanation: 'La represión del alzamiento de 1956 incluyó fusilamientos, narrados por Rodolfo Walsh en "Operación Masacre".' }),
  mc({ id: 'gna-his-per-25', subject: S, block: 'peronismo_y_posperonismo', topic: 'onania_gobierno', difficulty: 3,
    stem: 'La "Revolución Argentina" iniciada en 1966 se propuso:',
    choices: [{ t: 'un gobierno militar autoritario y de duración indefinida.', ok: true }, { t: 'convocar elecciones inmediatas.' }, { t: 'restaurar la Constitución de 1949.' }, { t: 'entregar el poder al peronismo.' }],
    explanation: 'A diferencia de golpes previos, la "Revolución Argentina" pretendió instaurar un régimen militar permanente.' }),
  mc({ id: 'gna-his-per-26', subject: S, block: 'peronismo_y_posperonismo', topic: 'lanusse_gan', difficulty: 3,
    stem: 'El "Gran Acuerdo Nacional" (GAN) impulsado por Lanusse buscaba:',
    choices: [{ t: 'una salida electoral con retorno del peronismo.', ok: true }, { t: 'perpetuar la dictadura.' }, { t: 'expulsar a los inmigrantes.' }, { t: 'privatizar YPF.' }],
    explanation: 'Lanusse promovió el GAN para encauzar una salida electoral que incluyera (con límites) al peronismo, en 1973.' }),
  mc({ id: 'gna-his-per-27', subject: S, block: 'peronismo_y_posperonismo', topic: 'illia_petroleo', difficulty: 3,
    stem: 'El gobierno de Illia (1963-1966) se caracterizó, entre otras medidas, por:',
    choices: [{ t: 'anular contratos petroleros y sancionar la ley de medicamentos.', ok: true }, { t: 'crear la convertibilidad.' }, { t: 'privatizar los ferrocarriles.' }, { t: 'declarar la guerra a Chile.' }],
    explanation: 'Illia anuló contratos petroleros firmados por Frondizi e impulsó políticas de control de precios de medicamentos.' }),

  // ---- Proceso y democracia ----
  mc({ id: 'gna-his-dem-21', subject: S, block: 'proceso_y_democracia', topic: 'mundial_78', difficulty: 3,
    stem: 'El Mundial de Fútbol de 1978, ganado por Argentina, se disputó durante:',
    choices: [{ t: 'la última dictadura militar.', ok: true }, { t: 'el gobierno de Alfonsín.' }, { t: 'el gobierno de Perón.' }, { t: 'la presidencia de Menem.' }],
    explanation: 'El Mundial 78 se jugó bajo la dictadura, que lo utilizó con fines propagandísticos.' }),
  mc({ id: 'gna-his-dem-22', subject: S, block: 'proceso_y_democracia', topic: 'deuda_externa', difficulty: 3,
    stem: 'Durante la última dictadura, la deuda externa argentina:',
    choices: [{ t: 'creció fuertemente.', ok: true }, { t: 'fue totalmente cancelada.' }, { t: 'se mantuvo en cero.' }, { t: 'fue asumida por Gran Bretaña.' }],
    explanation: 'La política económica de la dictadura multiplicó la deuda externa del país.' }),
  mc({ id: 'gna-his-dem-23', subject: S, block: 'proceso_y_democracia', topic: 'elecciones_1983', difficulty: 2,
    stem: 'En las elecciones de 1983, Raúl Alfonsín se impuso como candidato de:',
    choices: [{ t: 'la Unión Cívica Radical.', ok: true }, { t: 'el Partido Justicialista.' }, { t: 'el PAN.' }, { t: 'la Alianza.' }],
    explanation: 'Alfonsín ganó las elecciones de 1983 por la UCR, frente al justicialismo.' }),
  mc({ id: 'gna-his-dem-24', subject: S, block: 'proceso_y_democracia', topic: 'juicio_juntas_resultado', difficulty: 3,
    stem: 'El Juicio a las Juntas (1985) tuvo como resultado:',
    choices: [{ t: 'la condena de excomandantes como Videla y Massera.', ok: true }, { t: 'la absolución de todos los acusados.' }, { t: 'la anulación de la democracia.' }, { t: 'un nuevo golpe de Estado.' }],
    explanation: 'El juicio condenó a varios excomandantes por los crímenes de la dictadura, entre ellos Videla y Massera.' }),
  mc({ id: 'gna-his-dem-25', subject: S, block: 'proceso_y_democracia', topic: 'levantamientos_carapintadas', difficulty: 3,
    stem: 'Los alzamientos militares "carapintadas" durante el gobierno de Alfonsín presionaron por:',
    choices: [{ t: 'frenar los juicios por violaciones a los derechos humanos.', ok: true }, { t: 'restaurar el peronismo.' }, { t: 'privatizar empresas.' }, { t: 'recuperar Malvinas.' }],
    explanation: 'Los levantamientos carapintadas presionaron por leyes de impunidad como Obediencia Debida.' }),
  mc({ id: 'gna-his-dem-26', subject: S, block: 'proceso_y_democracia', topic: 'convertibilidad_ministro', difficulty: 3,
    stem: 'El ministro de Economía que implementó la convertibilidad en 1991 fue:',
    choices: [{ t: 'Domingo Cavallo.', ok: true }, { t: 'José Martínez de Hoz.' }, { t: 'Roberto Lavagna.' }, { t: 'Bernardo Grinspun.' }],
    explanation: 'Domingo Cavallo, ministro de Menem, lanzó la Ley de Convertibilidad (1 peso = 1 dólar) en 1991.' }),
  mc({ id: 'gna-his-dem-27', subject: S, block: 'proceso_y_democracia', topic: 'indultos', difficulty: 3,
    stem: 'A comienzos de los años 90, el presidente Menem dispuso:',
    choices: [{ t: 'indultos a militares condenados por la dictadura.', ok: true }, { t: 'la reapertura de todos los juicios.' }, { t: 'la estatización de la banca.' }, { t: 'la recuperación de Malvinas.' }],
    explanation: 'Menem indultó (1989-1990) a jefes militares condenados y a otros procesados.' }),
  mc({ id: 'gna-his-dem-28', subject: S, block: 'proceso_y_democracia', topic: 'reforma_94_contenido', difficulty: 3,
    stem: 'Entre las novedades de la reforma constitucional de 1994 se cuenta:',
    choices: [{ t: 'la incorporación del Jefe de Gabinete y del Consejo de la Magistratura.', ok: true }, { t: 'la eliminación del Senado.' }, { t: 'la supresión del federalismo.' }, { t: 'la instauración de la monarquía.' }],
    explanation: 'La reforma de 1994 creó el Jefe de Gabinete, el Consejo de la Magistratura y dio jerarquía a tratados de DD.HH.' }),
  mc({ id: 'gna-his-dem-29', subject: S, block: 'proceso_y_democracia', topic: 'de_la_rua_alianza', difficulty: 3,
    stem: 'Fernando de la Rúa llegó a la presidencia en 1999 como candidato de:',
    choices: [{ t: 'la Alianza (UCR-Frepaso).', ok: true }, { t: 'el Partido Justicialista.' }, { t: 'el PAN.' }, { t: 'la CGT.' }],
    explanation: 'De la Rúa ganó en 1999 al frente de la Alianza entre la UCR y el Frepaso.' }),
  mc({ id: 'gna-his-dem-30', subject: S, block: 'proceso_y_democracia', topic: 'corralito', difficulty: 3,
    stem: 'La restricción a la extracción de depósitos bancarios que agravó la crisis de 2001 se conoció como:',
    choices: [{ t: 'el "corralito".', ok: true }, { t: 'la convertibilidad.' }, { t: 'el Plan Austral.' }, { t: 'el Rodrigazo.' }],
    explanation: 'El "corralito" (2001) limitó el retiro de efectivo de los bancos y profundizó el estallido social.' }),

  // ================= Tanda 5 =================
  mc({ id: 'gna-his-ind-33', subject: S, block: 'independencia_y_anarquia', topic: 'sobremonte', difficulty: 3,
    stem: 'Durante la primera invasión inglesa (1806), el virrey Sobremonte:',
    choices: [{ t: 'huyó de Buenos Aires con los caudales.', ok: true }, { t: 'organizó la defensa personalmente.' }, { t: 'declaró la Independencia.' }, { t: 'firmó la Constitución.' }],
    explanation: 'El virrey Sobremonte abandonó la ciudad, lo que desprestigió a las autoridades españolas.' }),
  mc({ id: 'gna-his-ind-34', subject: S, block: 'independencia_y_anarquia', topic: 'junta_grande', difficulty: 3,
    stem: 'La incorporación de los diputados del interior a la Junta a fines de 1810 dio lugar a la:',
    choices: [{ t: 'Junta Grande.', ok: true }, { t: 'Asamblea del Año XIII.' }, { t: 'Constitución de 1819.' }, { t: 'Confederación.' }],
    explanation: 'La Junta Grande resultó de sumar a los diputados provinciales a la Primera Junta.' }),
  mc({ id: 'gna-his-ind-35', subject: S, block: 'independencia_y_anarquia', topic: 'triunviratos', difficulty: 3,
    stem: 'Después de las Juntas, el poder ejecutivo quedó a cargo de órganos colegiados de tres miembros llamados:',
    choices: [{ t: 'Triunviratos.', ok: true }, { t: 'Directorios.' }, { t: 'Consulados.' }, { t: 'Cabildos.' }],
    explanation: 'El Primer y Segundo Triunvirato ejercieron el ejecutivo entre 1811 y 1814.' }),
  mc({ id: 'gna-his-ind-36', subject: S, block: 'independencia_y_anarquia', topic: 'san_martin_yapeyu', difficulty: 3,
    stem: 'José de San Martín nació en:',
    choices: [{ t: 'Yapeyú (actual Corrientes).', ok: true }, { t: 'Buenos Aires.' }, { t: 'Mendoza.' }, { t: 'Tucumán.' }],
    explanation: 'San Martín nació en Yapeyú en 1778 y se formó militarmente en España.' }),
  mc({ id: 'gna-his-ind-37', subject: S, block: 'independencia_y_anarquia', topic: 'presidente_congreso', difficulty: 3,
    stem: 'Presidía el Congreso de Tucumán, el día de la Declaración de la Independencia:',
    choices: [{ t: 'Francisco Narciso de Laprida.', ok: true }, { t: 'Manuel Belgrano.' }, { t: 'Bernardino Rivadavia.' }, { t: 'Cornelio Saavedra.' }],
    explanation: 'Francisco Narciso de Laprida presidía la sesión del 9 de julio de 1816.' }),
  mc({ id: 'gna-his-ind-38', subject: S, block: 'independencia_y_anarquia', topic: 'belgrano_economista', difficulty: 3,
    stem: 'Antes de su actuación militar, Manuel Belgrano se desempeñó como:',
    choices: [{ t: 'secretario del Consulado y difusor de ideas económicas.', ok: true }, { t: 'virrey del Río de la Plata.' }, { t: 'gobernador de Buenos Aires.' }, { t: 'general realista.' }],
    explanation: 'Belgrano fue secretario del Real Consulado y promovió la educación, la industria y la agricultura.' }),
  mc({ id: 'gna-his-ind-39', subject: S, block: 'independencia_y_anarquia', topic: 'pueyrredon', difficulty: 3,
    stem: 'Al momento de la Declaración de la Independencia, el Director Supremo era:',
    choices: [{ t: 'Juan Martín de Pueyrredón.', ok: true }, { t: 'Bernardino Rivadavia.' }, { t: 'Cornelio Saavedra.' }, { t: 'Justo José de Urquiza.' }],
    explanation: 'Pueyrredón, Director Supremo desde 1816, apoyó decisivamente la campaña de San Martín.' }),
  mc({ id: 'gna-his-ind-40', subject: S, block: 'independencia_y_anarquia', topic: 'guemes_muerte', difficulty: 3,
    stem: 'Martín Miguel de Güemes murió en 1821:',
    choices: [{ t: 'a causa de heridas en combate contra los realistas.', ok: true }, { t: 'exiliado en Europa.' }, { t: 'en la batalla de Caseros.' }, { t: 'fusilado por Lavalle.' }],
    explanation: 'Güemes fue herido de muerte en un ataque realista a Salta en 1821.' }),

  mc({ id: 'gna-his-org-26', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'dorrego', difficulty: 3,
    stem: 'El gobernador federal Manuel Dorrego fue fusilado en 1828 por orden de:',
    choices: [{ t: 'Juan Lavalle.', ok: true }, { t: 'Juan Manuel de Rosas.' }, { t: 'Justo José de Urquiza.' }, { t: 'Bartolomé Mitre.' }],
    explanation: 'El unitario Juan Lavalle hizo fusilar a Dorrego, hecho que agravó la guerra civil.' }),
  mc({ id: 'gna-his-org-27', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'quiroga', difficulty: 3,
    stem: 'El caudillo riojano Facundo Quiroga fue asesinado en 1835 en:',
    choices: [{ t: 'Barranca Yaco.', ok: true }, { t: 'la Vuelta de Obligado.' }, { t: 'Caseros.' }, { t: 'San Lorenzo.' }],
    explanation: 'Quiroga fue emboscado y asesinado en Barranca Yaco (Córdoba) en 1835.' }),
  mc({ id: 'gna-his-org-28', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'echeverria', difficulty: 3,
    stem: 'La obra literaria "El Matadero", crítica al rosismo, pertenece a:',
    choices: [{ t: 'Esteban Echeverría.', ok: true }, { t: 'Domingo Sarmiento.' }, { t: 'José Hernández.' }, { t: 'Juan B. Alberdi.' }],
    explanation: 'Echeverría, de la Generación del 37, escribió "El Matadero" y el "Dogma Socialista".' }),
  mc({ id: 'gna-his-org-29', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'alberdi_frase', difficulty: 3,
    stem: 'La frase "gobernar es poblar" se atribuye a:',
    choices: [{ t: 'Juan Bautista Alberdi.', ok: true }, { t: 'Bartolomé Mitre.' }, { t: 'Julio A. Roca.' }, { t: 'Nicolás Avellaneda.' }],
    explanation: 'Alberdi sintetizó en "gobernar es poblar" la necesidad de fomentar la inmigración.' }),
  mc({ id: 'gna-his-org-30', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'mitre_historiador', difficulty: 3,
    stem: 'Además de militar y presidente, Bartolomé Mitre fue reconocido como:',
    choices: [{ t: 'historiador y fundador del diario La Nación.', ok: true }, { t: 'compositor del Himno.' }, { t: 'creador de la bandera.' }, { t: 'primer gobernador de Entre Ríos.' }],
    explanation: 'Mitre escribió obras históricas (sobre Belgrano y San Martín) y fundó el diario La Nación en 1870.' }),
  mc({ id: 'gna-his-org-31', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'ley_aduana', difficulty: 3,
    stem: 'La Ley de Aduanas de 1835, sancionada bajo Rosas, buscó:',
    choices: [{ t: 'proteger la producción del interior frente a la importación.', ok: true }, { t: 'abrir totalmente el comercio.' }, { t: 'prohibir la ganadería.' }, { t: 'crear el Banco Central.' }],
    explanation: 'La Ley de Aduana estableció aranceles proteccionistas para ciertas producciones del interior.' }),
  mc({ id: 'gna-his-org-32', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'martin_fierro', difficulty: 3,
    stem: 'El poema "Martín Fierro", que refleja la vida del gaucho, fue escrito por:',
    choices: [{ t: 'José Hernández.', ok: true }, { t: 'Esteban Echeverría.' }, { t: 'Domingo Sarmiento.' }, { t: 'Leopoldo Lugones.' }],
    explanation: 'José Hernández publicó "El gaucho Martín Fierro" (1872), obra cumbre de la literatura gauchesca.' }),

  mc({ id: 'gna-his-est-21', subject: S, block: 'estado_nacional', topic: 'juarez_celman', difficulty: 3,
    stem: 'El sistema de concentración de poder durante la presidencia de Juárez Celman se llamó:',
    choices: [{ t: 'el "unicato".', ok: true }, { t: 'el "corralito".' }, { t: 'la "convertibilidad".' }, { t: 'la "década infame".' }],
    explanation: 'El "unicato" describía el poder personal de Juárez Celman, jefe del PAN, hasta la crisis de 1890.' }),
  mc({ id: 'gna-his-est-22', subject: S, block: 'estado_nacional', topic: 'ley_inmigracion', difficulty: 3,
    stem: 'La Ley de Inmigración y Colonización de 1876 (Ley Avellaneda) buscaba:',
    choices: [{ t: 'fomentar y organizar la llegada de inmigrantes.', ok: true }, { t: 'expulsar a los extranjeros.' }, { t: 'crear la moneda nacional.' }, { t: 'nacionalizar el petróleo.' }],
    explanation: 'La ley promovió la inmigración europea, clave del modelo agroexportador.' }),
  mc({ id: 'gna-his-est-23', subject: S, block: 'estado_nacional', topic: 'capital_federal', difficulty: 2,
    stem: 'La ciudad de Buenos Aires es la Capital Federal de la República desde:',
    choices: [{ t: '1880.', ok: true }, { t: '1810.' }, { t: '1853.' }, { t: '1994.' }],
    explanation: 'La federalización de Buenos Aires como Capital se concretó por ley en 1880.' }),
  mc({ id: 'gna-his-est-24', subject: S, block: 'estado_nacional', topic: 'lugones', difficulty: 3,
    stem: 'Una figura destacada de la cultura del Centenario (1910) fue el escritor:',
    choices: [{ t: 'Leopoldo Lugones.', ok: true }, { t: 'Julio Cortázar.' }, { t: 'Jorge Luis Borges.' }, { t: 'Roberto Arlt.' }],
    explanation: 'Leopoldo Lugones fue una figura literaria central hacia el Centenario de 1910.' }),

  mc({ id: 'gna-his-rad-16', subject: S, block: 'radicales_y_conservadores', topic: 'yrigoyen_apodo', difficulty: 3,
    stem: 'Hipólito Yrigoyen era popularmente apodado:',
    choices: [{ t: '"el Peludo".', ok: true }, { t: '"el Restaurador".' }, { t: '"el Libertador".' }, { t: '"el Zorro".' }],
    explanation: 'Por su carácter reservado, a Yrigoyen se lo apodaba "el Peludo".' }),
  mc({ id: 'gna-his-rad-17', subject: S, block: 'radicales_y_conservadores', topic: 'ortiz_castillo', difficulty: 3,
    stem: 'El presidente conservador que intentó combatir el fraude, pero enfermó y fue reemplazado por Ramón Castillo, fue:',
    choices: [{ t: 'Roberto M. Ortiz.', ok: true }, { t: 'Agustín P. Justo.' }, { t: 'José F. Uriburu.' }, { t: 'Marcelo T. de Alvear.' }],
    explanation: 'Roberto Ortiz buscó elecciones limpias, pero su enfermedad llevó a Castillo al poder.' }),
  mc({ id: 'gna-his-rad-18', subject: S, block: 'radicales_y_conservadores', topic: 'gou', difficulty: 3,
    stem: 'La logia militar que participó del golpe de 1943 se conoció como:',
    choices: [{ t: 'el GOU.', ok: true }, { t: 'la Logia Lautaro.' }, { t: 'la Triple A.' }, { t: 'la Liga Patriótica.' }],
    explanation: 'El GOU (Grupo de Oficiales Unidos) fue clave en el golpe de 1943, del que surgió Perón.' }),

  mc({ id: 'gna-his-per-28', subject: S, block: 'peronismo_y_posperonismo', topic: 'braden_o_peron', difficulty: 3,
    stem: 'La consigna "Braden o Perón" de 1946 enfrentaba a Perón con:',
    choices: [{ t: 'la injerencia del embajador estadounidense.', ok: true }, { t: 'la Unión Soviética.' }, { t: 'el Reino Unido.' }, { t: 'la Iglesia.' }],
    explanation: 'La campaña de 1946 opuso a Perón con el embajador de EE.UU., Spruille Braden, símbolo de la intromisión extranjera.' }),
  mc({ id: 'gna-his-per-29', subject: S, block: 'peronismo_y_posperonismo', topic: 'reeleccion_1952', difficulty: 3,
    stem: 'Gracias a la Constitución de 1949, Perón pudo ser:',
    choices: [{ t: 'reelegido en 1952.', ok: true }, { t: 'senador vitalicio.' }, { t: 'presidente de la Corte.' }, { t: 'gobernador de Buenos Aires.' }],
    explanation: 'La reforma de 1949 habilitó la reelección; Perón fue reelecto en 1952, con Eva ya muy enferma.' }),
  mc({ id: 'gna-his-per-30', subject: S, block: 'peronismo_y_posperonismo', topic: 'eva_muerte', difficulty: 2,
    stem: 'Eva Perón falleció en:',
    choices: [{ t: '1952.', ok: true }, { t: '1945.' }, { t: '1955.' }, { t: '1974.' }],
    explanation: 'Eva Perón murió el 26 de julio de 1952, poco después de la reelección de Perón.' }),
  mc({ id: 'gna-his-per-31', subject: S, block: 'peronismo_y_posperonismo', topic: 'peron_exilio', difficulty: 3,
    stem: 'Tras su derrocamiento en 1955, Perón pasó buena parte de su exilio en:',
    choices: [{ t: 'España.', ok: true }, { t: 'Estados Unidos.' }, { t: 'la Unión Soviética.' }, { t: 'el Reino Unido.' }],
    explanation: 'Perón se exilió en varios países y finalmente se estableció en Madrid, España.' }),
  mc({ id: 'gna-his-per-32', subject: S, block: 'peronismo_y_posperonismo', topic: 'bastones_largos', difficulty: 3,
    stem: 'La "Noche de los Bastones Largos" (1966) fue la represión a:',
    choices: [{ t: 'profesores y estudiantes en las universidades.', ok: true }, { t: 'obreros ferroviarios.' }, { t: 'militares carapintadas.' }, { t: 'las Madres de Plaza de Mayo.' }],
    explanation: 'En 1966, el gobierno de Onganía intervino las universidades reprimiendo a docentes y estudiantes.' }),
  mc({ id: 'gna-his-per-33', subject: S, block: 'peronismo_y_posperonismo', topic: 'ezeiza', difficulty: 3,
    stem: 'El regreso definitivo de Perón al país en 1973 estuvo marcado por hechos de violencia conocidos como:',
    choices: [{ t: 'la masacre de Ezeiza.', ok: true }, { t: 'el Cordobazo.' }, { t: 'la Semana Trágica.' }, { t: 'el Rodrigazo.' }],
    explanation: 'El 20 de junio de 1973, el regreso de Perón derivó en enfrentamientos armados en Ezeiza.' }),
  mc({ id: 'gna-his-per-34', subject: S, block: 'peronismo_y_posperonismo', topic: 'rodrigazo', difficulty: 3,
    stem: 'El "Rodrigazo" (1975), durante el gobierno de Isabel Perón, fue:',
    choices: [{ t: 'un fuerte ajuste económico con devaluación e inflación.', ok: true }, { t: 'un golpe militar.' }, { t: 'una reforma constitucional.' }, { t: 'una guerra externa.' }],
    explanation: 'El plan del ministro Celestino Rodrigo (1975) provocó devaluación y estallido inflacionario.' }),

  mc({ id: 'gna-his-dem-31', subject: S, block: 'proceso_y_democracia', topic: 'esma', difficulty: 3,
    stem: 'Uno de los mayores centros clandestinos de detención de la dictadura funcionó en:',
    choices: [{ t: 'la ESMA (Escuela de Mecánica de la Armada).', ok: true }, { t: 'la Casa Rosada.' }, { t: 'el Congreso.' }, { t: 'la Universidad de Buenos Aires.' }],
    explanation: 'La ESMA fue uno de los principales centros clandestinos de detención y tortura entre 1976 y 1983.' }),
  mc({ id: 'gna-his-dem-32', subject: S, block: 'proceso_y_democracia', topic: 'malvinas_fechas', difficulty: 3,
    stem: 'El desembarco argentino en Malvinas fue el 2 de abril de 1982 y la rendición se produjo el:',
    choices: [{ t: '14 de junio de 1982.', ok: true }, { t: '25 de mayo de 1982.' }, { t: '9 de julio de 1982.' }, { t: '20 de junio de 1982.' }],
    explanation: 'La guerra duró unas diez semanas: del 2 de abril al 14 de junio de 1982.' }),
  mc({ id: 'gna-his-dem-33', subject: S, block: 'proceso_y_democracia', topic: 'plan_austral', difficulty: 3,
    stem: 'El plan económico de Alfonsín que en 1985 creó una nueva moneda para frenar la inflación fue:',
    choices: [{ t: 'el Plan Austral.', ok: true }, { t: 'la Convertibilidad.' }, { t: 'el Rodrigazo.' }, { t: 'el Plan Quinquenal.' }],
    explanation: 'El Plan Austral (1985) reemplazó el peso argentino por el austral para combatir la inflación.' }),
  mc({ id: 'gna-his-dem-34', subject: S, block: 'proceso_y_democracia', topic: 'menem_reeleccion', difficulty: 3,
    stem: 'Gracias a la reforma constitucional de 1994, Carlos Menem pudo:',
    choices: [{ t: 'ser reelecto presidente en 1995.', ok: true }, { t: 'gobernar de forma vitalicia.' }, { t: 'disolver el Congreso.' }, { t: 'suprimir las provincias.' }],
    explanation: 'La reforma habilitó una reelección inmediata; Menem fue reelecto en 1995.' }),
  mc({ id: 'gna-his-dem-35', subject: S, block: 'proceso_y_democracia', topic: 'cinco_presidentes', difficulty: 3,
    stem: 'La crisis de diciembre de 2001 se caracterizó, en pocos días, por:',
    choices: [{ t: 'la sucesión de varios presidentes en menos de dos semanas.', ok: true }, { t: 'un golpe militar exitoso.' }, { t: 'la recuperación de Malvinas.' }, { t: 'la sanción de una nueva Constitución.' }],
    explanation: 'Tras la renuncia de De la Rúa, se sucedieron varios presidentes provisionales en pocos días.' }),
  mc({ id: 'gna-his-dem-36', subject: S, block: 'proceso_y_democracia', topic: 'fin_convertibilidad', difficulty: 3,
    stem: 'La salida de la convertibilidad, con una fuerte devaluación, se produjo en 2002 durante la presidencia de:',
    choices: [{ t: 'Eduardo Duhalde.', ok: true }, { t: 'Fernando de la Rúa.' }, { t: 'Néstor Kirchner.' }, { t: 'Carlos Menem.' }],
    explanation: 'En 2002, el gobierno de Duhalde abandonó la paridad 1 a 1 y devaluó el peso.' }),
  mc({ id: 'gna-his-dem-37', subject: S, block: 'proceso_y_democracia', topic: 'kirchner_2003', difficulty: 2,
    stem: 'Tras la crisis, en 2003 asumió la presidencia:',
    choices: [{ t: 'Néstor Kirchner.', ok: true }, { t: 'Mauricio Macri.' }, { t: 'Raúl Alfonsín.' }, { t: 'Adolfo Rodríguez Saá.' }],
    explanation: 'Néstor Kirchner asumió en mayo de 2003, tras la etapa de transición de Duhalde.' }),
  mc({ id: 'gna-his-dem-38', subject: S, block: 'proceso_y_democracia', topic: 'derechos_humanos_anulacion', difficulty: 3,
    stem: 'En 2003 el Congreso declaró la nulidad de las leyes de Punto Final y Obediencia Debida, lo que permitió:',
    choices: [{ t: 'reabrir los juicios por delitos de la dictadura.', ok: true }, { t: 'indultar a los militares.' }, { t: 'privatizar YPF.' }, { t: 'restaurar la convertibilidad.' }],
    explanation: 'La nulidad de esas leyes habilitó la reapertura de los juicios por crímenes de lesa humanidad.' }),
  mc({ id: 'gna-his-dem-39', subject: S, block: 'proceso_y_democracia', topic: 'saenz_pena_democracia', difficulty: 2,
    stem: 'Desde 1983, la Argentina vive el período democrático:',
    choices: [{ t: 'más prolongado y continuo de su historia.', ok: true }, { t: 'más breve de su historia.' }, { t: 'interrumpido por golpes cada dos años.' }, { t: 'bajo un régimen monárquico.' }],
    explanation: 'Desde 1983, sin interrupciones militares, transcurre el ciclo democrático más largo del país.' }),
  mc({ id: 'gna-his-dem-40', subject: S, block: 'proceso_y_democracia', topic: 'malvinas_soberania', difficulty: 2,
    stem: 'La Constitución reformada en 1994 ratifica que la recuperación de las Islas Malvinas debe lograrse:',
    choices: [{ t: 'por la vía pacífica y respetando el modo de vida de sus habitantes.', ok: true }, { t: 'únicamente por la fuerza militar.' }, { t: 'renunciando a la soberanía.' }, { t: 'cediéndolas a un tercer país.' }],
    explanation: 'La disposición transitoria primera reafirma la soberanía sobre Malvinas por medios pacíficos.' }),

  // ================= Tanda 6 (cierre) =================
  mc({ id: 'gna-his-ind-41', subject: S, block: 'independencia_y_anarquia', topic: 'primer_gobierno_patrio', difficulty: 1,
    stem: 'La Revolución de Mayo de 1810 dio origen al primer gobierno patrio en reemplazo del:',
    choices: [{ t: 'virrey.', ok: true }, { t: 'presidente.' }, { t: 'gobernador federal.' }, { t: 'director supremo.' }],
    explanation: 'La Primera Junta reemplazó la autoridad del virrey Cisneros.' }),
  mc({ id: 'gna-his-ind-42', subject: S, block: 'independencia_y_anarquia', topic: 'fecha_independencia', difficulty: 1,
    stem: 'La Independencia argentina se conmemora cada:',
    choices: [{ t: '9 de julio.', ok: true }, { t: '25 de mayo.' }, { t: '20 de junio.' }, { t: '17 de agosto.' }],
    explanation: 'El 9 de julio de 1816 se declaró la Independencia; el 25 de mayo recuerda la Revolución de 1810.' }),
  mc({ id: 'gna-his-ind-43', subject: S, block: 'independencia_y_anarquia', topic: 'san_martin_fallecimiento', difficulty: 3,
    stem: 'José de San Martín falleció en 1850 en:',
    choices: [{ t: 'Boulogne-sur-Mer, Francia.', ok: true }, { t: 'Buenos Aires.' }, { t: 'Lima, Perú.' }, { t: 'Yapeyú.' }],
    explanation: 'San Martín murió exiliado en Francia; el 17 de agosto se recuerda su paso a la inmortalidad.' }),
  mc({ id: 'gna-his-org-33', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'pavon_anio', difficulty: 2,
    stem: 'La batalla de Pavón, que abrió paso a la unificación nacional, se libró en:',
    choices: [{ t: '1861.', ok: true }, { t: '1852.' }, { t: '1820.' }, { t: '1880.' }],
    explanation: 'Pavón (1861) permitió a Mitre encabezar la unificación del país.' }),
  mc({ id: 'gna-his-org-34', subject: S, block: 'rosas_y_organizacion_nacional', topic: 'constitucion_autores', difficulty: 3,
    stem: 'La Constitución de 1853 fue sancionada por un Congreso Constituyente reunido en:',
    choices: [{ t: 'Santa Fe.', ok: true }, { t: 'Buenos Aires.' }, { t: 'Tucumán.' }, { t: 'Córdoba.' }],
    explanation: 'El Congreso Constituyente que sancionó la Constitución de 1853 sesionó en la ciudad de Santa Fe.' }),
  mc({ id: 'gna-his-est-25', subject: S, block: 'estado_nacional', topic: 'centenario', difficulty: 2,
    stem: 'En 1910 la Argentina celebró el Centenario de:',
    choices: [{ t: 'la Revolución de Mayo.', ok: true }, { t: 'la Independencia.' }, { t: 'la Constitución.' }, { t: 'la fundación de Buenos Aires.' }],
    explanation: 'El Centenario de 1910 conmemoró los 100 años de la Revolución de Mayo de 1810.' }),
  mc({ id: 'gna-his-est-26', subject: S, block: 'estado_nacional', topic: 'saenz_pena_secreto', difficulty: 2,
    stem: 'El principal aporte de la Ley Sáenz Peña a la vida política fue garantizar el voto:',
    choices: [{ t: 'secreto (además de universal y obligatorio).', ok: true }, { t: 'calificado por la renta.' }, { t: 'a viva voz.' }, { t: 'solo para propietarios.' }],
    explanation: 'El carácter secreto del voto terminó con las prácticas de presión y fraude de la época.' }),
  mc({ id: 'gna-his-rad-19', subject: S, block: 'radicales_y_conservadores', topic: 'ucr_origen', difficulty: 2,
    stem: 'La Unión Cívica Radical (UCR) fue fundada en la década de:',
    choices: [{ t: '1890.', ok: true }, { t: '1850.' }, { t: '1930.' }, { t: '1945.' }],
    explanation: 'La UCR surgió a partir de la Unión Cívica y la Revolución del Parque de 1890.' }),
  mc({ id: 'gna-his-rad-20', subject: S, block: 'radicales_y_conservadores', topic: 'yrigoyen_dos_presidencias', difficulty: 3,
    stem: 'Hipólito Yrigoyen fue presidente en:',
    choices: [{ t: 'dos oportunidades (1916-1922 y 1928-1930).', ok: true }, { t: 'una sola oportunidad.' }, { t: 'tres oportunidades.' }, { t: 'ninguna (solo fue candidato).' }],
    explanation: 'Yrigoyen gobernó dos veces; su segundo mandato fue interrumpido por el golpe de 1930.' }),
  mc({ id: 'gna-his-per-35', subject: S, block: 'peronismo_y_posperonismo', topic: 'tres_banderas', difficulty: 3,
    stem: 'Las "tres banderas" históricas del peronismo son:',
    choices: [{ t: 'justicia social, independencia económica y soberanía política.', ok: true }, { t: 'orden, progreso y administración.' }, { t: 'libertad, igualdad y fraternidad.' }, { t: 'paz, pan y trabajo.' }],
    explanation: 'El peronismo sintetizó su doctrina en la justicia social, la independencia económica y la soberanía política.' }),
  mc({ id: 'gna-his-per-36', subject: S, block: 'peronismo_y_posperonismo', topic: 'peron_fallecimiento', difficulty: 2,
    stem: 'Juan Domingo Perón falleció, ejerciendo su tercera presidencia, en:',
    choices: [{ t: '1974.', ok: true }, { t: '1955.' }, { t: '1983.' }, { t: '1952.' }],
    explanation: 'Perón murió el 1 de julio de 1974 y lo sucedió su vicepresidenta, Isabel.' }),
  mc({ id: 'gna-his-dem-41', subject: S, block: 'proceso_y_democracia', topic: 'nunca_mas', difficulty: 2,
    stem: 'El informe de la CONADEP sobre los desaparecidos se tituló:',
    choices: [{ t: '"Nunca Más".', ok: true }, { t: '"Operación Masacre".' }, { t: '"El Matadero".' }, { t: '"Facundo".' }],
    explanation: 'El informe "Nunca Más" (1984) documentó las desapariciones durante la dictadura.' }),
];
