import type { Item } from '../../../types/content';

// Ítems recuperados a mano desde el preguntero original (reference/EJERCITACION-
// QUIMICA.pdf). El importador los había roto al fusionar las columnas de
// opciones; acá se reconstruyen con las opciones reales y la respuesta
// verificada. Reemplazan a los qui-imp-* deprecados equivalentes.
export const items: Item[] = [
  {
    id: 'qui-rec-0005',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'conceptos_basicos_y_sistemas_materiales',
    topic: 'conceptos_basicos_y_sistemas_materiales',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 1,
    stem: '¿Cuál de las siguientes propiedades NO cambia si cambia la cantidad de materia de una sustancia?',
    choices: [
      { id: 'a', text: 'Densidad', correct: true },
      { id: 'b', text: 'Longitud', correct: false },
      { id: 'c', text: 'Volumen', correct: false },
      { id: 'd', text: 'Peso', correct: false },
      { id: 'e', text: 'Área', correct: false },
    ],
    explanation:
      'La densidad es una propiedad intensiva: no depende de la cantidad de materia. Longitud, volumen, peso y área son extensivas (cambian con la cantidad).',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 6, "Conceptos básicos y sistemas materiales").',
  },
  {
    id: 'qui-rec-0006',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'conceptos_basicos_y_sistemas_materiales',
    topic: 'conceptos_basicos_y_sistemas_materiales',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 2,
    stem: 'Si se aumenta bruscamente la temperatura de un sólido o se disminuye mucho su presión, se convertirá en gas sin pasar por el estado líquido. Este proceso se denomina:',
    choices: [
      { id: 'a', text: 'Volatilización', correct: true },
      { id: 'b', text: 'Ebullición', correct: false },
      { id: 'c', text: 'Licuefacción', correct: false },
      { id: 'd', text: 'Solidificación', correct: false },
      { id: 'e', text: 'Fusión', correct: false },
    ],
    explanation:
      'El pasaje directo de sólido a gas (sin pasar por líquido) es la volatilización o sublimación. La ebullición y la fusión pasan por el estado líquido; la licuefacción es gas → líquido.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 15, "Conceptos básicos y sistemas materiales").',
  },
  {
    id: 'qui-rec-0033',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'unidades_quimicas',
    topic: 'unidades_quimicas',
    track: 'teorico',
    type: 'true_false_series',
    frequency: 'media',
    difficulty: 2,
    stem: 'Si el peso molecular del O₂ es 32, clasificá como verdadero (V) o falso (F):',
    statements: [
      { text: 'En 32 g de O₂ hay un mol de moléculas de O₂.', correct: true },
      { text: 'En 32 g de O₂ hay una molécula-gramo de O₂.', correct: true },
      { text: 'En 32 g de O₂ hay un mol de átomos de O.', correct: false },
      { text: 'En 32 g de O₂ hay un átomo-gramo de O.', correct: false },
      { text: 'En 32 g de O₂ hay 2 átomos-gramo de O.', correct: true },
      { text: 'En 32 g de O₂ hay 6,02×10²³ átomos de O.', correct: false },
      { text: 'En 32 g de O₂ hay 1,204×10²⁴ átomos de O.', correct: true },
    ],
    explanation:
      '32 g de O₂ = 1 mol de moléculas (V) = 1 molécula-gramo (V). Como cada molécula tiene 2 átomos de O, hay 2 mol de átomos = 2 át-gr = 1,204×10²⁴ átomos de O. Por eso "1 mol de átomos", "1 át-gr" y "6,02×10²³ átomos" son falsas.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 13, "Unidades Químicas").',
  },
  {
    id: 'qui-rec-0036',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'unidades_quimicas',
    topic: 'unidades_quimicas',
    track: 'teorico',
    type: 'true_false_series',
    frequency: 'media',
    difficulty: 3,
    stem: 'Clasificá como verdadero (V) o falso (F):',
    statements: [
      { text: 'En 3 moles de NH₃ hay 3 átomos de N y 9 átomos de H.', correct: false },
      { text: 'En 3 moles de NH₃ hay 1 mol de átomos de N y 3 moles de átomos de H.', correct: false },
      { text: 'En 3 moles de NH₃ hay 3 moles de átomos de N y 9 moles de átomos de H.', correct: true },
      { text: 'En 32 g de O₂ hay 6,02×10²³ moléculas y 1,204×10²⁴ átomos.', correct: true },
      { text: 'En 32 g de O₂ hay 1 átomo-gramo de oxígeno.', correct: false },
      { text: 'En 142 g de Cl₂ hay 4 moles de moléculas de cloro.', correct: false },
      { text: 'En 142 g de Cl₂ hay 4 átomos-gramo de cloro.', correct: true },
    ],
    explanation:
      '3 mol de NH₃ → 3 mol de átomos de N y 9 mol de átomos de H (no "3 átomos"). 32 g de O₂ = 1 mol = 6,02×10²³ moléculas y 1,204×10²⁴ átomos (2 át-gr). 142 g de Cl₂ = 2 mol de moléculas → 4 át-gr de Cl (no 4 mol de moléculas).',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 24, "Unidades Químicas").',
  },
  {
    id: 'qui-rec-0046',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'unidades_quimicas',
    topic: 'unidades_quimicas',
    track: 'practico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 3,
    stem: '¿Cuál de las siguientes muestras, todas ellas de 100 g, posee mayor cantidad de átomos de H?',
    choices: [
      { id: 'a', text: 'H₂O', correct: false },
      { id: 'b', text: 'C₂H₄', correct: true },
      { id: 'c', text: 'NaOH', correct: false },
      { id: 'd', text: 'HLi', correct: false },
      { id: 'e', text: 'H₃PO₄', correct: false },
    ],
    explanation:
      'Moles de H por 100 g: C₂H₄ (M=28) → 100/28×4 ≈ 14,3 mol H; HLi (M=8) → 12,5 mol; H₂O → 11,1; H₃PO₄ → 3,1; NaOH → 2,5. El máximo es C₂H₄.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 35, "Unidades Químicas").',
  },
  {
    id: 'qui-rec-0048',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'unidades_quimicas',
    topic: 'unidades_quimicas',
    track: 'practico',
    type: 'true_false_series',
    frequency: 'media',
    difficulty: 3,
    stem: 'Determiná si las siguientes afirmaciones son verdaderas (V) o falsas (F):',
    statements: [
      { text: 'En 126 g de H₂O hay 4,214×10²⁴ moléculas.', correct: true },
      { text: 'En 31 g de H₂CO₃ hay 9,03×10²³ átomos de O.', correct: true },
      { text: 'En 100 g de CO₂ hay 4,104×10²⁴ átomos totales.', correct: true },
      { text: 'En 11,2 litros de N₂ hay 3,01×10²³ moléculas en CNPyT.', correct: true },
      { text: '3,01×10²³ moléculas de H₂S pesan 34 g.', correct: false },
      { text: 'En 5,01×10²³ moléculas de H₃PO₄ hay 0,83 át-gr de P.', correct: true },
      { text: 'En 15 litros de NH₃ hay 1,61×10²³ átomos totales.', correct: false },
    ],
    explanation:
      '126 g H₂O = 7 mol → 4,214×10²⁴ moléc (V). 31 g H₂CO₃ = 0,5 mol → 1,5 mol O = 9,03×10²³ átomos O (V). 100 g CO₂ = 2,27 mol → 6,82 mol átomos = 4,10×10²⁴ (V). 11,2 L N₂ (CNPT) = 0,5 mol = 3,01×10²³ moléc (V). 3,01×10²³ moléc de H₂S = 0,5 mol = 17 g, no 34 g (F). 5,01×10²³ moléc H₃PO₄ = 0,83 mol → 0,83 át-gr P (V). 15 L NH₃ = 0,67 mol → 4 átomos c/u = 1,61×10²⁴ átomos, no 10²³ (F).',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 37, "Unidades Químicas").',
  },
  {
    id: 'qui-rec-0082',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'teoria_atomica',
    topic: 'teoria_atomica',
    track: 'practico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 2,
    stem: '¿Cuál es el número másico de un elemento cuyo ión X⁺² tiene 20 neutrones y 18 electrones?',
    choices: [
      { id: 'a', text: '40', correct: true },
      { id: 'b', text: '45', correct: false },
      { id: 'c', text: '20', correct: false },
      { id: 'd', text: '18', correct: false },
      { id: 'e', text: 'Ninguna es correcta', correct: false },
    ],
    explanation:
      'El ión X⁺² perdió 2 electrones, así que el átomo neutro tiene 18 + 2 = 20 electrones = 20 protones (Z = 20). Número másico A = Z + neutrones = 20 + 20 = 40.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 42, "Teoría Atómica").',
  },
  {
    id: 'qui-rec-0083',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'teoria_atomica',
    topic: 'teoria_atomica',
    track: 'practico',
    type: 'single_choice',
    frequency: 'baja',
    difficulty: 1,
    stem: '¿Cuál es el número atómico de un elemento cuyo ión monovalente negativo tiene 45 neutrones y su Z = 35?',
    choices: [
      { id: 'a', text: '35', correct: true },
      { id: 'b', text: '36', correct: false },
      { id: 'c', text: '45', correct: false },
      { id: 'd', text: '80', correct: false },
      { id: 'e', text: 'Ninguna es correcta', correct: false },
    ],
    explanation:
      'El número atómico (Z) es la cantidad de protones y no cambia al formarse el ión: el dato Z = 35 ya es la respuesta. (Los electrones cambian al ganar/perder carga, pero Z no.)',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 43, "Teoría Atómica").',
  },
  {
    id: 'qui-rec-0102',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'tabla_periodica',
    topic: 'tabla_periodica',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 1,
    stem: '¿Cuál de los siguientes elementos pertenece a la familia de los alcalinos térreos?',
    choices: [
      { id: 'a', text: 'Ba', correct: true },
      { id: 'b', text: 'Na', correct: false },
      { id: 'c', text: 'S', correct: false },
      { id: 'd', text: 'Fe', correct: false },
      { id: 'e', text: 'F', correct: false },
    ],
    explanation:
      'Los alcalinotérreos son el Grupo 2 (Be, Mg, Ca, Sr, Ba, Ra). El bario (Ba) pertenece a esa familia. El Na es alcalino (Grupo 1) y el F es halógeno.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 8, "Tabla Periódica").',
  },
  {
    id: 'qui-rec-0106',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'tabla_periodica',
    topic: 'tabla_periodica',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 1,
    stem: '¿Qué halógeno está ubicado en el periodo 3?',
    choices: [
      { id: 'a', text: 'F', correct: false },
      { id: 'b', text: 'Cl', correct: true },
      { id: 'c', text: 'S', correct: false },
      { id: 'd', text: 'Br', correct: false },
      { id: 'e', text: 'K', correct: false },
    ],
    explanation:
      'Los halógenos son el Grupo 17. El del periodo 3 es el cloro (Cl). El flúor está en el periodo 2 y el bromo en el 4; el S no es halógeno y el K es alcalino.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 16, "Tabla Periódica").',
  },
  {
    id: 'qui-rec-0109',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'tabla_periodica',
    topic: 'tabla_periodica',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 2,
    stem: 'Considerá los siguientes elementos y seleccioná los que son halógenos: Li − F − As − Br − Ag',
    choices: [
      { id: 'a', text: 'Li, F y Ag', correct: false },
      { id: 'b', text: 'As y Br', correct: false },
      { id: 'c', text: 'Br y F', correct: true },
      { id: 'd', text: 'Br', correct: false },
      { id: 'e', text: 'F y Ag', correct: false },
    ],
    explanation:
      'Los halógenos del grupo son el flúor (F) y el bromo (Br). El Li es alcalino, el As es del grupo del nitrógeno y la Ag es un metal de transición.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 19, "Tabla Periódica").',
  },
  {
    id: 'qui-rec-0113',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'tabla_periodica',
    topic: 'tabla_periodica',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 2,
    stem: '¿Cuál de los siguientes elementos posee mayor radio atómico?',
    choices: [
      { id: 'a', text: 'F', correct: false },
      { id: 'b', text: 'Rb', correct: true },
      { id: 'c', text: 'Ca', correct: false },
      { id: 'd', text: 'Cl', correct: false },
      { id: 'e', text: 'Sr', correct: false },
    ],
    explanation:
      'El radio atómico crece hacia la izquierda y hacia abajo en la tabla. El Rb (Grupo 1, periodo 5) es el más grande de la lista; el Sr le sigue, y F/Cl son pequeños por estar arriba y a la derecha.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 26, "Tabla Periódica").',
  },
  {
    id: 'qui-rec-0193',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'soluciones',
    topic: 'concentracion',
    track: 'practico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 1,
    stem: '¿Cuántos gramos de sulfuro ferroso hay en 240 g de solución al 33 % P/P?',
    choices: [
      { id: 'a', text: '79,2 g', correct: true },
      { id: 'b', text: '42,8 g', correct: false },
      { id: 'c', text: '82,5 g', correct: false },
      { id: 'd', text: '33,3 g', correct: false },
      { id: 'e', text: '24 g', correct: false },
    ],
    explanation:
      'El 33 % P/P significa 33 g de soluto por cada 100 g de solución. En 240 g: 240 × 0,33 = 79,2 g.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 7, "Soluciones").',
  },
  {
    id: 'qui-rec-0216',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'soluciones',
    topic: 'diluciones',
    track: 'practico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 3,
    stem: 'Se toman 16 mL de una solución de H₂SO₄ 1,8 N y se prepara una solución 0,25 N. ¿Qué volumen de agua se agregó?',
    choices: [
      { id: 'a', text: '99,2 mL', correct: true },
      { id: 'b', text: '115,2 mL', correct: false },
      { id: 'c', text: '16 mL', correct: false },
      { id: 'd', text: 'Faltan datos', correct: false },
      { id: 'e', text: 'Ninguna es correcta', correct: false },
    ],
    explanation:
      'Por dilución N₁·V₁ = N₂·V₂ → V₂ = 16 × 1,8 / 0,25 = 115,2 mL (volumen final). El agua agregada es V₂ − V₁ = 115,2 − 16 = 99,2 mL. (115,2 mL es el volumen final, no el agua agregada.)',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 57, "Soluciones").',
  },
  {
    id: 'qui-rec-0218',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'soluciones',
    topic: 'diluciones',
    track: 'practico',
    type: 'single_choice',
    frequency: 'baja',
    difficulty: 3,
    stem: 'Se mezcla un volumen desconocido de solución 0,28 M de sulfato ferroso con 50 mL de otra solución del mismo soluto rotulada 0,18 N, y se prepara 250 mL de solución final 0,032 M. ¿Qué volumen de agua se agregó?',
    choices: [
      { id: 'a', text: '12,5 mL', correct: false },
      { id: 'b', text: '187,5 mL', correct: true },
      { id: 'c', text: '200 mL', correct: false },
      { id: 'd', text: '175 mL', correct: false },
      { id: 'e', text: 'Ninguna es correcta', correct: false },
    ],
    explanation:
      'Sulfato ferroso (Fe²⁺): 0,18 N = 0,09 M. Moles finales = 0,032 × 0,25 = 0,008. De los 50 mL: 0,09 × 0,05 = 0,0045 mol. Del volumen desconocido: 0,28·V = 0,008 − 0,0045 = 0,0035 → V = 12,5 mL. Agua = 250 − 50 − 12,5 = 187,5 mL.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 60, "Soluciones").',
  },
  {
    id: 'qui-rec-0237',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'propiedades_coligativas',
    topic: 'propiedades_coligativas',
    track: 'practico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 3,
    stem: 'Una solución contiene 25 g de un compuesto orgánico y 600 g de agua. Si el punto de ebullición de la solución es 100,156 °C, calculá el peso molecular del soluto. (Keb del agua = 0,52 °C/m)',
    choices: [
      { id: 'a', text: '25', correct: false },
      { id: 'b', text: '139', correct: true },
      { id: 'c', text: '239', correct: false },
      { id: 'd', text: '300', correct: false },
      { id: 'e', text: 'Ninguna es correcta', correct: false },
    ],
    explanation:
      'ΔTeb = 100,156 − 100 = 0,156 °C. Molalidad m = ΔTeb / Keb = 0,156 / 0,52 = 0,3 mol/kg. Moles de soluto = 0,3 × 0,6 kg = 0,18. M = masa / moles = 25 / 0,18 ≈ 139 g/mol.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Recuperado del preguntero (nº 19, "Propiedades Coligativas").',
  },

  // --- Reescritos a partir de ejercicios multi-parte del preguntero ---
  {
    id: 'qui-rec-0004',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'conceptos_basicos_y_sistemas_materiales',
    topic: 'conceptos_basicos_y_sistemas_materiales',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 1,
    stem: '¿Cuál de las siguientes es una propiedad **extensiva** (depende de la cantidad de materia)?',
    choices: [
      { id: 'a', text: 'Masa', correct: true },
      { id: 'b', text: 'Densidad', correct: false },
      { id: 'c', text: 'Temperatura', correct: false },
      { id: 'd', text: 'Punto de fusión', correct: false },
      { id: 'e', text: 'Color', correct: false },
    ],
    explanation:
      'Las propiedades extensivas dependen de la cantidad de materia: masa, volumen, peso, longitud. La densidad, la temperatura, el punto de fusión y el color son intensivas (no cambian con la cantidad).',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Reescrito del preguntero (nº 5, "Conceptos básicos"), originalmente lista de clasificar E/I.',
  },
  {
    id: 'qui-rec-0133',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'formuleo',
    topic: 'formuleo',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 1,
    stem: 'La fórmula del **anhídrido carbónico** (dióxido de carbono) es:',
    choices: [
      { id: 'a', text: 'CO₂', correct: true },
      { id: 'b', text: 'CO', correct: false },
      { id: 'c', text: 'C₂O', correct: false },
      { id: 'd', text: 'CaO', correct: false },
    ],
    explanation:
      'El anhídrido carbónico es el óxido ácido del carbono con estado de oxidación +4: CO₂. El CO es el monóxido de carbono y el CaO es óxido de calcio.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Reescrito del preguntero (nº 2, "Formuleo"), originalmente lista de formular óxidos.',
  },
  {
    id: 'qui-rec-0134',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'formuleo',
    topic: 'formuleo',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 2,
    stem: 'La fórmula del **óxido de fósforo (III)** (anhídrido fosforoso) es:',
    choices: [
      { id: 'a', text: 'P₂O₃', correct: true },
      { id: 'b', text: 'P₂O₅', correct: false },
      { id: 'c', text: 'PO₃', correct: false },
      { id: 'd', text: 'P₃O₂', correct: false },
    ],
    explanation:
      'Con fósforo +3 y oxígeno −2, la fórmula neutra es P₂O₃. Con fósforo +5 sería P₂O₅ (anhídrido fosfórico).',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Reescrito del preguntero (nº 9, "Formuleo"), originalmente lista de formular.',
  },
  {
    id: 'qui-rec-0279',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'quimica_organica',
    topic: 'quimica_organica',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 3,
    stem: '¿Cuántos enlaces **π (pi)** presenta la molécula de 3,7-dihidroxi-oct-5-enal?',
    choices: [
      { id: 'a', text: '1', correct: false },
      { id: 'b', text: '2', correct: true },
      { id: 'c', text: '3', correct: false },
      { id: 'd', text: '4', correct: false },
    ],
    explanation:
      'La molécula (OHC–CH₂–CHOH–CH₂–CH=CH–CHOH–CH₃) tiene un doble enlace C=O del aldehído (1 π) y un doble enlace C=C entre los carbonos 5 y 6 (1 π): en total 2 enlaces π. Los grupos –OH son enlaces simples (σ).',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Reescrito del preguntero (nº 24, "Química Orgánica"), originalmente "dibujar y averiguar".',
  },
  {
    id: 'qui-rec-0280',
    institutions: ['UNC', 'UNSa'],
    subject: 'quimica',
    block: 'quimica_organica',
    topic: 'quimica_organica',
    track: 'teorico',
    type: 'single_choice',
    frequency: 'media',
    difficulty: 3,
    stem: '¿Cuántos carbonos **quirales** (asimétricos) tiene el ácido 2-amino-4-metil-pentanoico (leucina)?',
    choices: [
      { id: 'a', text: '0', correct: false },
      { id: 'b', text: '1', correct: true },
      { id: 'c', text: '2', correct: false },
      { id: 'd', text: '3', correct: false },
    ],
    explanation:
      'La estructura es HOOC–CH(NH₂)–CH₂–CH(CH₃)–CH₃. Solo el C2 (unido a –COOH, –NH₂, –H y la cadena) tiene cuatro sustituyentes distintos → es quiral. El C4 tiene dos metilos iguales, así que no es asimétrico: hay 1 carbono quiral.',
    source: 'original',
    version: 1,
    status: 'active',
    authorNote: 'Reescrito del preguntero (nº 25, "Química Orgánica"), originalmente "dibujar y averiguar".',
  },
];
